<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_aux" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="373"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="UT_AuxiliaryInputMapping" Type="UT_AuxiliaryInputMapping_Type_02_Bool_NonLatched" Comment="" x="-1600.0" y="-1066.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="255" Comment=""/>
			<Parameter Name="u16ObjId_1" Value="AuxInput_Automatik_ein" Comment=""/>
			<Parameter Name="DigitalInput_1" Value="'SlurryTanker.Automatik.Automatik_ein.AuxInput_Automatik_ein'" Comment=""/>
			<Parameter Name="u16ObjId_2" Value="AuxInput_Auseinanderklappen" Comment=""/>
			<Parameter Name="DigitalInput_2" Value="'AuxInput_Auseinanderklappen'" Comment=""/>
			<Parameter Name="u16ObjId_3" Value="AuxInput_Verteiler_senken" Comment=""/>
			<Parameter Name="DigitalInput_3" Value="'AuxInput_Verteiler_senken'" Comment=""/>
			<Parameter Name="u16ObjId_4" Value="AuxInput_Knickdeichsel_senken" Comment=""/>
			<Parameter Name="DigitalInput_4" Value="'AuxInput_Knickdeichsel_senken'" Comment=""/>
			<Parameter Name="u16ObjId_5" Value="AuxInput_Automatik_aus" Comment=""/>
			<Parameter Name="DigitalInput_5" Value="'AuxInput_Automatik_aus'" Comment=""/>
			<Parameter Name="u16ObjId_6" Value="AuxInput_Zusammenklappen" Comment=""/>
			<Parameter Name="DigitalInput_6" Value="'AuxInput_Zusammenklappen'" Comment=""/>
			<Parameter Name="u16ObjId_7" Value="AuxInput_Verteiler_heben" Comment=""/>
			<Parameter Name="DigitalInput_7" Value="'AuxInput_Verteiler_heben'" Comment=""/>
			<Parameter Name="u16ObjId_8" Value="AuxInput_Knickdeichsel_heben" Comment=""/>
			<Parameter Name="DigitalInput_8" Value="'AuxInput_Knickdeichsel_heben'" Comment=""/>
		</FB>
		<FB Name="UT_AuxiliaryInputMapping_1" Type="UT_AuxiliaryInputMapping_Type_02_Bool_NonLatched" Comment="" x="-1600.0" y="1600.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="255" Comment=""/>
			<Parameter Name="u16ObjId_2" Value="AuxInput_Dom" Comment=""/>
			<Parameter Name="DigitalInput_2" Value="'AuxInput_Dom'" Comment=""/>
			<Parameter Name="u16ObjId_3" Value="AuxInput_Heckschieber" Comment=""/>
			<Parameter Name="DigitalInput_3" Value="'AuxInput_Heckschieber'" Comment=""/>
			<Parameter Name="u16ObjId_5" Value="AuxInput_Schneidwerk" Comment=""/>
			<Parameter Name="DigitalInput_5" Value="'AuxInput_Schneidwerk'" Comment=""/>
			<Parameter Name="u16ObjId_6" Value="AuxInput_Seitenschieber" Comment=""/>
			<Parameter Name="DigitalInput_6" Value="'AuxInput_Seitenschieber'" Comment=""/>
			<Parameter Name="u16ObjId_7" Value="AuxInput_Abscheider" Comment=""/>
			<Parameter Name="DigitalInput_7" Value="'AuxInput_Abscheider'" Comment=""/>
			<Parameter Name="u16ObjId_8" Value="AuxInput_Licht" Comment=""/>
			<Parameter Name="DigitalInput_8" Value="'AuxInput_Licht'" Comment=""/>
		</FB>
		<FB Name="UT_AuxiliaryInputMapping_2" Type="UT_AuxiliaryInputMapping_Type_02_Bool_NonLatched" Comment="" x="-2100.0" y="4400.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="255" Comment=""/>
			<Parameter Name="u16ObjId_1" Value="PAGE_1_AUX" Comment=""/>
			<Parameter Name="DigitalInput_1" Value="'PAGE_1_AUX'" Comment=""/>
			<Parameter Name="u16ObjId_2" Value="PAGE_2_AUX" Comment=""/>
			<Parameter Name="DigitalInput_2" Value="'PAGE_2_AUX'" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="UT_AuxiliaryInputMapping.INIT" Comment="" dx1="80.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="UT_AuxiliaryInputMapping_1.INIT" Comment="" dx1="80.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="UT_AuxiliaryInputMapping_2.INIT" Comment="" dx1="80.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
