<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_DataPanel" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DataPanel_xDB_16_DO_SAE_J1939" Type="Hutschienenmoped_XL_8_DO" Comment="" x="1246.6666666666667" y="13.333333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="224" Comment=""/>
			<Parameter Name="u16ObjId" Value="65535" Comment=""/>
			<Parameter Name="DigitalOutput_Q1" Value="'SlurryTanker.Schneidwerk.rechtslauf'" Comment=""/>
			<Parameter Name="DigitalOutput_Q2" Value="'SlurryTanker.Schneidwerk.linkslauf'" Comment=""/>
			<Parameter Name="DigitalOutput_Q3" Value="'SlurryTanker.Vorsteuerventil_2A.QX'" Comment=""/>
			<Parameter Name="DigitalOutput_Q4" Value="'SlurryTanker.Vorsteuerventil_2B.QX'" Comment=""/>
			<Parameter Name="DigitalOutput_Q5" Value="'SlurryTanker.Klappen.Sitzventile.QXA'" Comment=""/>
			<Parameter Name="DigitalOutput_Q6" Value="'SlurryTanker.Klappen.Sitzventile.QXB'" Comment=""/>
			<Parameter Name="DigitalOutput_Q7" Value="'SlurryTanker.Verteiler.Sitzventile.QXA'" Comment=""/>
			<Parameter Name="DigitalOutput_Q8" Value="'SlurryTanker.Verteiler.Sitzventile.QXB'" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DataPanel_xDB_16_DO_SAE_J1939.INIT" Comment="" dx1="640.0" dx2="640.0" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
