<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_DataPanel" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DataPanel_xDB_16_DO_SAE_J1939" Type="DataPanel_xDB_16_DO_SAE_J1939" Comment="" x="1246.6666666666667" y="13.333333333333334">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="224"/>
			<Parameter Name="u16ObjId" Value="65535"/>
			<Parameter Name="DigitalOutput_1A" Value="'Schneidwerk_rechtslauf_1A'"/>
			<Parameter Name="DigitalOutput_1B" Value="'Schneidwerk_linkslauf_1B'"/>
			<Parameter Name="DigitalOutput_2A" Value="'Vorsteuerventil_2A'"/>
			<Parameter Name="DigitalOutput_2B" Value="'Vorsteuerventil_2B'"/>
			<Parameter Name="DigitalOutput_3A" Value="'Klappen_3A'"/>
			<Parameter Name="DigitalOutput_3B" Value="'Klappen_3B'"/>
			<Parameter Name="DigitalOutput_4A" Value="'Verteiler_4A'"/>
			<Parameter Name="DigitalOutput_4B" Value="'Verteiler_4B'"/>
			<Parameter Name="DigitalOutput_5A" Value="'Knickdeichsel_5A'"/>
			<Parameter Name="DigitalOutput_5B" Value="'Knickdeichsel_5B'"/>
			<Parameter Name="DigitalOutput_6A" Value="'Dom_6A'"/>
			<Parameter Name="DigitalOutput_6B" Value="'Heckschieber_6B'"/>
			<Parameter Name="DigitalOutput_7A" Value="'Seitenschieber_7A'"/>
			<Parameter Name="DigitalOutput_7B" Value="'Abscheider_7B'"/>
			<Parameter Name="DigitalOutput_8A" Value="'Licht_8A'"/>
			<Parameter Name="DigitalOutput_8B" Value="'frei_8B'"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DataPanel_xDB_16_DO_SAE_J1939.INIT" Comment="" dx1="640.0"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
