<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_DataPanel" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DataPanel_xDB_16_DO_SAE_J1939" Type="DataPanel_xDB_16_DO_SAE_J1939" Comment="" x="1246.6666666666667" y="13.333333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="224" Comment=""/>
			<Parameter Name="u16ObjId" Value="65535" Comment=""/>
			<Parameter Name="DigitalOutput_1A" Value="'Schneidwerk_rechtslauf_1A'" Comment=""/>
			<Parameter Name="DigitalOutput_1B" Value="'Schneidwerk_linkslauf_1B'" Comment=""/>
			<Parameter Name="DigitalOutput_2A" Value="'Vorsteuerventil_2A'" Comment=""/>
			<Parameter Name="DigitalOutput_2B" Value="'Vorsteuerventil_2B'" Comment=""/>
			<Parameter Name="DigitalOutput_3A" Value="'Klappen_3A'" Comment=""/>
			<Parameter Name="DigitalOutput_3B" Value="'Klappen_3B'" Comment=""/>
			<Parameter Name="DigitalOutput_4A" Value="'Verteiler_4A'" Comment=""/>
			<Parameter Name="DigitalOutput_4B" Value="'Verteiler_4B'" Comment=""/>
			<Parameter Name="DigitalOutput_5A" Value="'Knickdeichsel_5A'" Comment=""/>
			<Parameter Name="DigitalOutput_5B" Value="'Knickdeichsel_5B'" Comment=""/>
			<Parameter Name="DigitalOutput_6A" Value="'Dom_6A'" Comment=""/>
			<Parameter Name="DigitalOutput_6B" Value="'Heckschieber_6B'" Comment=""/>
			<Parameter Name="DigitalOutput_7A" Value="'Seitenschieber_7A'" Comment=""/>
			<Parameter Name="DigitalOutput_7B" Value="'Abscheider_7B'" Comment=""/>
			<Parameter Name="DigitalOutput_8A" Value="'Licht_8A'" Comment=""/>
			<Parameter Name="DigitalOutput_8B" Value="'frei_8B'" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DataPanel_xDB_16_DO_SAE_J1939.INIT" Comment="" dx1="640.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
