<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_aux" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="373"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="UT_AuxiliaryInputMapping" Type="UT_AuxiliaryInputMapping" Comment="" x="-1600.0" y="-1066.6666666666667">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="255"/>
			<Parameter Name="u16ObjId_1" Value="AuxInput_Automatik_ein"/>
			<Parameter Name="DigitalInput_1" Value="&quot;AuxInput_Automatik_ein&quot;"/>
			<Parameter Name="u16ObjId_2" Value="31003"/>
			<Parameter Name="DigitalInput_2" Value="&quot;AuxInput_Auseinanderklappen&quot;"/>
			<Parameter Name="u16ObjId_3" Value="31004"/>
			<Parameter Name="DigitalInput_3" Value="&quot;AuxInput_Verteiler_senken&quot;"/>
			<Parameter Name="u16ObjId_4" Value="31005"/>
			<Parameter Name="DigitalInput_4" Value="&quot;AuxInput_Knickdeichsel_senken&quot;"/>
			<Parameter Name="u16ObjId_5" Value="31006"/>
			<Parameter Name="DigitalInput_5" Value="&quot;AuxInput_Automatik_aus&quot;"/>
			<Parameter Name="u16ObjId_6" Value="31009"/>
			<Parameter Name="DigitalInput_6" Value="&quot;AuxInput_Zusammenklappen&quot;"/>
			<Parameter Name="u16ObjId_7" Value="31010"/>
			<Parameter Name="DigitalInput_7" Value="&quot;AuxInput_Verteiler_heben&quot;"/>
			<Parameter Name="u16ObjId_8" Value="31011"/>
			<Parameter Name="DigitalInput_8" Value="&quot;AuxInput_Knickdeichsel_heben&quot;"/>
		</FB>
		<FB Name="UT_AuxiliaryInputMapping_1" Type="UT_AuxiliaryInputMapping" Comment="" x="-1600.0" y="1600.0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="255"/>
			<Parameter Name="u16ObjId_2" Value="31001"/>
			<Parameter Name="DigitalInput_2" Value="&quot;AuxInput_Dom&quot;"/>
			<Parameter Name="u16ObjId_3" Value="31002"/>
			<Parameter Name="DigitalInput_3" Value="&quot;AuxInput_Heckschieber&quot;"/>
			<Parameter Name="u16ObjId_5" Value="31007"/>
			<Parameter Name="DigitalInput_5" Value="&quot;AuxInput_Schneidwerk&quot;"/>
			<Parameter Name="u16ObjId_6" Value="31008"/>
			<Parameter Name="DigitalInput_6" Value="&quot;AuxInput_Seitenschieber&quot;"/>
			<Parameter Name="u16ObjId_7" Value="31015"/>
			<Parameter Name="DigitalInput_7" Value="&quot;AuxInput_Abscheider&quot;"/>
			<Parameter Name="u16ObjId_8" Value="31016"/>
			<Parameter Name="DigitalInput_8" Value="&quot;AuxInput_Licht&quot;"/>
		</FB>
		<FB Name="UT_AuxiliaryInputMapping_2" Type="UT_AuxiliaryInputMapping" Comment="" x="-2100.0" y="4400.0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="255"/>
			<Parameter Name="u16ObjId_1" Value="31024"/>
			<Parameter Name="DigitalInput_1" Value="&quot;PAGE_1_AUX&quot;"/>
			<Parameter Name="u16ObjId_2" Value="31025"/>
			<Parameter Name="DigitalInput_2" Value="&quot;PAGE_2_AUX&quot;"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="UT_AuxiliaryInputMapping.INIT" Comment="" dx1="80.0"/>
			<Connection Source="INIT" Destination="UT_AuxiliaryInputMapping_1.INIT" Comment="" dx1="80.0"/>
			<Connection Source="INIT" Destination="UT_AuxiliaryInputMapping_2.INIT" Comment="" dx1="80.0"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
