<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Vorsteuerventil" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="REQ1" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="REQ2" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="REQ3" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="REQ4" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="REQ5" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="IN1" Type="BOOL"/>
			<VarDeclaration Name="IN2" Type="BOOL"/>
			<VarDeclaration Name="IN3" Type="BOOL"/>
			<VarDeclaration Name="IN4" Type="BOOL"/>
			<VarDeclaration Name="IN5" Type="BOOL"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="OR_5" Type="OR_5" x="1100" y="253.33">
		</FB>
		<FB Name="QX" Type="QX" x="2560" y="0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="REQ1" Destination="OR_5.REQ" dx1="546.67"/>
			<Connection Source="REQ2" Destination="OR_5.REQ" dx1="553.33"/>
			<Connection Source="REQ3" Destination="OR_5.REQ" dx1="553.33"/>
			<Connection Source="REQ4" Destination="OR_5.REQ" dx1="553.33"/>
			<Connection Source="REQ5" Destination="OR_5.REQ" dx1="553.33"/>
			<Connection Source="OR_5.CNF" Destination="QX.REQ" dx1="320"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="IN1" Destination="OR_5.IN1" dx1="846.67"/>
			<Connection Source="IN2" Destination="OR_5.IN2" dx1="666.67"/>
			<Connection Source="IN3" Destination="OR_5.IN3" dx1="566.67"/>
			<Connection Source="IN4" Destination="OR_5.IN4" dx1="440"/>
			<Connection Source="IN5" Destination="OR_5.IN5" dx1="253.33"/>
			<Connection Source="OR_5.OUT" Destination="QX.OUT" dx1="320"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
