<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Vorsteuerventil" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="REQ1" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="REQ2" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="REQ3" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="REQ4" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="REQ5" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="IN1" Type="BOOL" Comment=""/>
			<VarDeclaration Name="IN2" Type="BOOL" Comment=""/>
			<VarDeclaration Name="IN3" Type="BOOL" Comment=""/>
			<VarDeclaration Name="IN4" Type="BOOL" Comment=""/>
			<VarDeclaration Name="IN5" Type="BOOL" Comment=""/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="OR_5" Type="OR_5" Comment="" x="1100.0" y="253.33333333333334">
		</FB>
		<FB Name="QX" Type="QX" Comment="" x="2560.0" y="0.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="REQ1" Destination="OR_5.REQ" Comment="" dx1="546.6666666666667"/>
			<Connection Source="REQ2" Destination="OR_5.REQ" Comment="" dx1="553.3333333333334"/>
			<Connection Source="REQ3" Destination="OR_5.REQ" Comment="" dx1="553.3333333333334"/>
			<Connection Source="REQ4" Destination="OR_5.REQ" Comment="" dx1="553.3333333333334"/>
			<Connection Source="REQ5" Destination="OR_5.REQ" Comment="" dx1="553.3333333333334"/>
			<Connection Source="INIT" Destination="QX.INIT" Comment="" dx1="2400.0" dx2="2400.0" dy="0.0"/>
			<Connection Source="OR_5.CNF" Destination="QX.REQ" Comment="" dx1="320.0" dx2="320.0" dy="0.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="IN1" Destination="OR_5.IN1" Comment="" dx1="846.6666666666667"/>
			<Connection Source="IN2" Destination="OR_5.IN2" Comment="" dx1="666.6666666666667"/>
			<Connection Source="IN3" Destination="OR_5.IN3" Comment="" dx1="566.6666666666667"/>
			<Connection Source="IN4" Destination="OR_5.IN4" Comment="" dx1="440.0"/>
			<Connection Source="IN5" Destination="OR_5.IN5" Comment="" dx1="253.33333333333334"/>
			<Connection Source="OR_5.OUT" Destination="QX.OUT" Comment="" dx1="320.0" dx2="320.0" dy="0.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
