<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Abscheider" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF_2a" Type="Event" Comment="">
				<With Var="OUT_2a"/>
			</SubAppEvent>
		</SubAppEventOutputs>
		<OutputVars>
			<VarDeclaration Name="OUT_2a" Type="BOOL" Comment=""/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AND_2_Abscheider" Type="AND_2" Comment="" x="4800.0" y="1066.6666666666667">
		</FB>
		<FB Name="E_T_FF_Abscheider" Type="E_T_FF" Comment="" x="1100.0" y="-700.0">
		</FB>
		<FB Name="Abscheider_7B" Type="QX" Comment="" x="4800.0" y="0.0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_IMPULSE_Abscheider" Type="E_IMPULSE" Comment="" x="2666.666666666667" y="0.0">
			<Parameter Name="TM" Value="T#3s"/>
		</FB>
		<SubApp Name="GreenWhiteBackground_Abscheider" Type="GreenWhiteBackground_Abscheider" Comment="" x="2666.666666666667" y="-1066.6666666666667">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="AuxInput_Abscheider_UP" Type="AuxInput_Abscheider_UP" Comment="" x="-1066.6666666666667" y="-533.3333333333334">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="SoftKey_Abscheider_UP" Type="SoftKey_Abscheider_UP" Comment="" x="-1066.6666666666667" y="-1066.6666666666667">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<EventConnections>
			<Connection Source="E_IMPULSE_Abscheider.CNF" Destination="AND_2_Abscheider.REQ" Comment="" dx1="473.33333333333337"/>
			<Connection Source="E_T_FF_Abscheider.EO" Destination="E_IMPULSE_Abscheider.REQ" Comment="" dx1="520.0"/>
			<Connection Source="E_IMPULSE_Abscheider.CNF" Destination="Abscheider_7B.REQ" Comment="" dx1="600.0"/>
			<Connection Source="AND_2_Abscheider.CNF" Destination="CNF_2a" Comment="" dx1="506.6666666666667"/>
			<Connection Source="INIT" Destination="Abscheider_7B.INIT" Comment="" dx1="5933.333333333334"/>
			<Connection Source="INIT" Destination="GreenWhiteBackground_Abscheider.INIT" Comment="" dx1="3620.0"/>
			<Connection Source="E_T_FF_Abscheider.EO" Destination="GreenWhiteBackground_Abscheider.EO" Comment="" dx1="206.66666666666669"/>
			<Connection Source="INIT" Destination="AuxInput_Abscheider_UP.INIT" Comment="" dx1="126.66666666666667"/>
			<Connection Source="AuxInput_Abscheider_UP.IND" Destination="E_T_FF_Abscheider.CLK" Comment="" dx1="466.6666666666667"/>
			<Connection Source="INIT" Destination="SoftKey_Abscheider_UP.INIT" Comment="" dx1="126.66666666666667"/>
			<Connection Source="SoftKey_Abscheider_UP.IND" Destination="E_T_FF_Abscheider.CLK" Comment="" dx1="506.6666666666667"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_IMPULSE_Abscheider.QO" Destination="AND_2_Abscheider.IN1" Comment="" dx1="366.6666666666667"/>
			<Connection Source="E_T_FF_Abscheider.Q" Destination="AND_2_Abscheider.IN2" Comment="" dx1="320.0"/>
			<Connection Source="E_IMPULSE_Abscheider.QO" Destination="Abscheider_7B.OUT" Comment="" dx1="580.0"/>
			<Connection Source="AND_2_Abscheider.OUT" Destination="OUT_2a" Comment="" dx1="613.3333333333334"/>
			<Connection Source="E_T_FF_Abscheider.Q" Destination="GreenWhiteBackground_Abscheider.Q" Comment="" dx1="313.33333333333337"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
