<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Schneidwerk" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="S_ON" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="S_OFF" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="u16ObjId" Type="UINT"/>
			<VarDeclaration Name="u16ObjIdA" Type="UINT"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="rechtslauf" Type="QX" x="5900" y="1400">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="E_T_FF_SR" Type="E_T_FF_SR" x="3200" y="1500">
		</FB>
		<FB Name="linkslauf" Type="QX" x="5900" y="-100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<SubApp Name="GreenWhiteBackground_Function" Type="GreenWhiteBackground_Function" x="5900" y="2200">
		</SubApp>
		<FB Name="SoftKey" Type="IE" x="100" y="980">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AuxInput" Type="IE" x="100" y="1800">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<Comment Comment="TODO: Schneidwerk linkslauf bei jedem 2. Start.  &#10;"  x="6800" y="0" width="1073.33" height="540"/>
		<EventConnections>
			<Connection Source="E_T_FF_SR.EO" Destination="rechtslauf.REQ"/>
			<Connection Source="S_ON" Destination="E_T_FF_SR.S" dx1="3300">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="S_OFF" Destination="E_T_FF_SR.R" dx1="3300">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_T_FF_SR.EO" Destination="GreenWhiteBackground_Function.EO" dx1="1400"/>
			<Connection Source="SoftKey.IND" Destination="E_T_FF_SR.CLK" dx1="1206.67"/>
			<Connection Source="AuxInput.IND" Destination="E_T_FF_SR.CLK" dx1="1206.67"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF_SR.Q" Destination="rechtslauf.OUT"/>
			<Connection Source="E_T_FF_SR.Q" Destination="GreenWhiteBackground_Function.Q" dx1="500"/>
			<Connection Source="u16ObjId" Destination="GreenWhiteBackground_Function.u16ObjId" dx1="3120">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="u16ObjIdA" Destination="GreenWhiteBackground_Function.u16ObjIdA" dx1="3120">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
