<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="AuxInput_Licht_UP" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-11">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="INITO" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="IND" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventOutputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_Licht_UP" Type="IE" Comment="" x="0.0" y="0.0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="SoftKey_Licht_UP.INIT" Comment=""/>
			<Connection Source="SoftKey_Licht_UP.INITO" Destination="INITO" Comment=""/>
			<Connection Source="SoftKey_Licht_UP.IND" Destination="IND" Comment=""/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
