<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GreenWhiteBackground_Licht" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-11">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="EO" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="Q" Type="BOOL" Comment=""/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="GreenWhiteBackground_Licht" Type="GreenWhiteBackground" Comment="" x="0.0" y="0.0">
			<Parameter Name="u16ObjId" Value="5016"/>
			<Parameter Name="u16ObjIdA" Value="31016"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="GreenWhiteBackground_Licht.INIT" Comment=""/>
			<Connection Source="EO" Destination="GreenWhiteBackground_Licht.REQ" Comment=""/>
		</EventConnections>
		<DataConnections>
			<Connection Source="Q" Destination="GreenWhiteBackground_Licht.DI1" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
