<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GreenWhiteBackground_Licht" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-11">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="20"/>
			</SubAppEvent>
			<SubAppEvent Name="EO" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="0"/>
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="Q" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="279"/>
			</VarDeclaration>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="GreenWhiteBackground_Licht" Type="GreenWhiteBackground" Comment="" x="-100.0" y="-800.0">
			<Parameter Name="u16ObjId" Value="5016"/>
			<Parameter Name="u16ObjIdA" Value="31016"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<EventConnections>
			<Connection Source="INIT" Destination="GreenWhiteBackground_Licht.INIT" Comment="" dx1="586.6666666666667" dx2="586.6666666666667" dy="0.0"/>
			<Connection Source="EO" Destination="GreenWhiteBackground_Licht.REQ" Comment="" dx1="400.0" dx2="400.0" dy="0.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="Q" Destination="GreenWhiteBackground_Licht.DI1" Comment="" dx1="506.6666666666667" dx2="506.6666666666667" dy="0.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
