<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Licht" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="Service Initialization">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_T_FF_Licht" Type="E_T_FF" Comment="" x="1520.0" y="193.33333333333334">
		</FB>
		<FB Name="Licht_8A" Type="QX" Comment="" x="2900.0" y="973.3333333333334">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<SubApp Name="GreenWhiteBackground_Licht" Type="GreenWhiteBackground_Licht" Comment="" x="4400.0" y="100.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="SoftKey_Licht_UP" Type="SoftKey_Licht_UP" Comment="" x="-700.0" y="0.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="AuxInput_Licht_UP" Type="AuxInput_Licht_UP" Comment="" x="-700.0" y="500.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<EventConnections>
			<Connection Source="E_T_FF_Licht.EO" Destination="Licht_8A.REQ" Comment="" dx1="126.66666666666667"/>
			<Connection Source="INIT" Destination="GreenWhiteBackground_Licht.INIT" Comment="" dx1="5253.333333333334"/>
			<Connection Source="E_T_FF_Licht.EO" Destination="GreenWhiteBackground_Licht.EO" Comment="" dx1="1160.0"/>
			<Connection Source="INIT" Destination="SoftKey_Licht_UP.INIT" Comment="" dx1="80.0" dx2="80.0" dy="0.0"/>
			<Connection Source="SoftKey_Licht_UP.IND" Destination="E_T_FF_Licht.CLK" Comment="" dx1="786.6666666666667" dx2="786.6666666666667" dy="0.0"/>
			<Connection Source="INIT" Destination="AuxInput_Licht_UP.INIT" Comment="" dx1="80.0" dx2="80.0" dy="0.0"/>
			<Connection Source="AuxInput_Licht_UP.IND" Destination="E_T_FF_Licht.CLK" Comment="" dx1="713.3333333333334" dx2="713.3333333333334" dy="0.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF_Licht.Q" Destination="Licht_8A.OUT" Comment="" dx1="60.0"/>
			<Connection Source="E_T_FF_Licht.Q" Destination="GreenWhiteBackground_Licht.Q" Comment="" dx1="1160.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
