<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="SlurryTanker" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-11">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<Group Name="func" Comment="" x="-920.0" y="-1200.0" width="5060.0" height="8940.0" locked="false">
		</Group>
		<Group Name="Vorsteuerventile" Comment="Vorsteuerventile" x="4266.666666666667" y="-1066.6666666666667" width="2940.0" height="3880.0" locked="false">
		</Group>
		<Group Name="Vorgewendeautomatik" Comment="Vorgewendeautomatik" x="-800.0" y="7866.666666666667" width="10000.0" height="4140.0" locked="false">
		</Group>
		<SubApp Name="mapping_Softkeys" Type="mapping_Softkeys" Comment="" x="460.0" y="4093.3333333333335">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="GroupName" Type="STRING" Value="func"/>
		</SubApp>
		<SubApp Name="mapping_DataPanel" Type="mapping_DataPanel" Comment="" x="460.0" y="3693.3333333333335">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="GroupName" Type="STRING" Value="func"/>
		</SubApp>
		<SubApp Name="mapping_aux" Type="mapping_aux" Comment="" x="460.0" y="4493.333333333334">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="GroupName" Type="STRING" Value="func"/>
		</SubApp>
		<SubApp Name="Automatik" Type="Automatik" Comment="" x="1126.6666666666667" y="706.6666666666667">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="GroupName" Type="STRING" Value="Vorgewendeautomatik"/>
		</SubApp>
		<SubApp Name="PAGES" Type="PAGES" Comment="" x="740.0" y="5326.666666666667">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="GroupName" Type="STRING" Value="func"/>
		</SubApp>
		<SubApp Name="mapping_Buttons" Type="mapping_Buttons" Comment="" x="606.6666666666667" y="4926.666666666667">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="GroupName" Type="STRING" Value="func"/>
		</SubApp>
		<SubApp Name="Dom" Type="TimedFunc" Comment="" x="1540.0" y="126.66666666666667">
			<Parameter Name="u16ObjId" Value="SoftKey_Dom" Comment=""/>
			<Parameter Name="u16ObjIdA" Value="AuxInput_Dom" Comment=""/>
			<Attribute Name="GroupName" Type="STRING" Value="func"/>
		</SubApp>
		<SubApp Name="Seitenschieber" Type="TimedFunc" Comment="" x="1540.0" y="793.3333333333334">
			<Parameter Name="u16ObjId" Value="SoftKey_Seitenschieber" Comment=""/>
			<Parameter Name="u16ObjIdA" Value="AuxInput_Seitenschieber" Comment=""/>
			<Attribute Name="GroupName" Type="STRING" Value="func"/>
		</SubApp>
		<SubApp Name="Klappen" Type="doppeltwirkend" Comment="" x="2073.3333333333335" y="7060.0">
			<Parameter Name="u16ObjId_heben" Value="SoftKey_Auseinanderklappen" Comment=""/>
			<Parameter Name="u16ObjId_senken" Value="SoftKey_Zusammenklappen" Comment=""/>
			<Parameter Name="u16ObjIdA_heben" Value="AuxInput_Auseinanderklappen" Comment=""/>
			<Parameter Name="u16ObjIdA_senken" Value="AuxInput_Zusammenklappen" Comment=""/>
			<Attribute Name="GroupName" Type="STRING" Value="func"/>
		</SubApp>
		<SubApp Name="Verteiler" Type="doppeltwirkend" Comment="" x="7013.333333333334" y="0.0">
			<Parameter Name="u16ObjId_heben" Value="SoftKey_Verteiler_heben" Comment=""/>
			<Parameter Name="u16ObjId_senken" Value="SoftKey_Verteiler_senken" Comment=""/>
			<Parameter Name="u16ObjIdA_heben" Value="AuxInput_Verteiler_heben" Comment=""/>
			<Parameter Name="u16ObjIdA_senken" Value="AuxInput_Verteiler_senken" Comment=""/>
			<Attribute Name="GroupName" Type="STRING" Value="Vorgewendeautomatik"/>
		</SubApp>
		<SubApp Name="Vorsteuerventil_2A" Type="Vorsteuerventil" Comment="" x="1440.0" y="133.33333333333334">
			<Attribute Name="GroupName" Type="STRING" Value="Vorsteuerventile"/>
		</SubApp>
		<SubApp Name="Vorsteuerventil_2B" Type="Vorsteuerventil" Comment="" x="1440.0" y="1866.6666666666667">
			<Attribute Name="GroupName" Type="STRING" Value="Vorsteuerventile"/>
		</SubApp>
		<SubApp Name="Knickdeichsel" Type="doppeltwirkend" Comment="" x="1940.0" y="1726.6666666666667">
			<Parameter Name="u16ObjId_heben" Value="SoftKey_Knickdeichsel_heben" Comment=""/>
			<Parameter Name="u16ObjId_senken" Value="SoftKey_Knickdeichsel_senken" Comment=""/>
			<Parameter Name="u16ObjIdA_heben" Value="AuxInput_Knickdeichsel_heben" Comment=""/>
			<Parameter Name="u16ObjIdA_senken" Value="AuxInput_Knickdeichsel_senken" Comment=""/>
			<Attribute Name="GroupName" Type="STRING" Value="func"/>
		</SubApp>
		<SubApp Name="Licht" Type="Dauerfunktion" Comment="" x="2206.666666666667" y="3060.0">
			<Parameter Name="u16ObjId" Value="SoftKey_Licht" Comment=""/>
			<Parameter Name="u16ObjIdA" Value="AuxInput_Licht" Comment=""/>
			<Attribute Name="GroupName" Type="STRING" Value="func"/>
		</SubApp>
		<SubApp Name="Abscheider" Type="TimedFunc" Comment="" x="2340.0" y="6126.666666666667">
			<Parameter Name="u16ObjId" Value="SoftKey_Abscheider" Comment=""/>
			<Parameter Name="u16ObjIdA" Value="AuxInput_Abscheider" Comment=""/>
			<Attribute Name="GroupName" Type="STRING" Value="func"/>
		</SubApp>
		<SubApp Name="Schneidwerk" Type="Schneidwerk" Comment="" x="7020.0" y="1326.6666666666667">
			<Parameter Name="u16ObjId" Value="SoftKey_Schneidwerk" Comment=""/>
			<Parameter Name="u16ObjIdA" Value="AuxInput_Schneidwerk" Comment=""/>
			<Attribute Name="GroupName" Type="STRING" Value="Vorgewendeautomatik"/>
		</SubApp>
		<SubApp Name="Heckschieber" Type="Heckschieber" Comment="" x="7020.0" y="2260.0">
			<Parameter Name="u16ObjId" Value="SoftKey_Heckschieber" Comment=""/>
			<Parameter Name="u16ObjIdA" Value="AuxInput_Heckschieber" Comment=""/>
			<Attribute Name="GroupName" Type="STRING" Value="Vorgewendeautomatik"/>
		</SubApp>
		<EventConnections>
			<Connection Source="INIT" Destination="mapping_Softkeys.INIT" Comment="" dx1="340.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="mapping_aux.INIT" Comment="" dx1="846.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="mapping_DataPanel.INIT" Comment="" dx1="846.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="Automatik.INIT" Comment="" dx1="11233.333333333334" dx2="53.333333333333336" dy="4126.666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="PAGES.INIT" Comment="" dx1="993.3333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="mapping_Buttons.INIT" Comment="" dx1="993.3333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="Dom.INIT" Comment="" dx1="1000.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="Seitenschieber.INIT" Comment="" dx1="1000.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="Klappen.INIT" Comment="" dx1="1266.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="Verteiler.INIT" Comment="" dx1="11340.0" dx2="11340.0" dy="4233.333333333334">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Automatik.EO_Verteiler_heben" Destination="Verteiler.EI_heben" Comment="" dx1="2073.3333333333335" dx2="2073.3333333333335" dy="0.0"/>
			<Connection Source="Automatik.EO_Verteiler_senken" Destination="Verteiler.EI_senken" Comment="" dx1="2060.0" dx2="2060.0" dy="0.0"/>
			<Connection Source="INIT" Destination="Vorsteuerventil_2A.INIT" Comment="" dx1="6826.666666666667" dx2="6826.666666666667" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Klappen.CNF_a" Destination="Vorsteuerventil_2A.REQ1" Comment="" dx1="1720.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Verteiler.CNF_a" Destination="Vorsteuerventil_2A.REQ3" Comment="" dx1="80.0" dx2="80.0" dy="-1226.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Dom.CNF" Destination="Vorsteuerventil_2A.REQ4" Comment="" dx1="2193.3333333333335" dx2="2193.3333333333335" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Seitenschieber.CNF" Destination="Vorsteuerventil_2A.REQ5" Comment="" dx1="2193.3333333333335" dx2="2193.3333333333335" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="Vorsteuerventil_2B.INIT" Comment="" dx1="4940.0" dx2="4940.0" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Klappen.CNF_b" Destination="Vorsteuerventil_2B.REQ1" Comment="" dx1="1720.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Verteiler.CNF_b" Destination="Vorsteuerventil_2B.REQ3" Comment="" dx1="80.0" dx2="80.0" dy="-920.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="Knickdeichsel.INIT" Comment="" dx1="1200.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Knickdeichsel.CNF_b" Destination="Vorsteuerventil_2B.REQ2" Comment="" dx1="1786.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Knickdeichsel.CNF_a" Destination="Vorsteuerventil_2A.REQ2" Comment="" dx1="1786.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="Licht.INIT" Comment="" dx1="1333.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="Abscheider.INIT" Comment="" dx1="1400.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Abscheider.CNF" Destination="Vorsteuerventil_2B.REQ5" Comment="" dx1="1693.3333333333335" dx2="1693.3333333333335" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="Schneidwerk.INIT" Comment="" dx1="3800.0" dx2="3800.0" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Automatik.EO_Automatik_ein" Destination="Schneidwerk.S_ON" Comment="" dx1="2106.666666666667" dx2="2106.666666666667" dy="0.0"/>
			<Connection Source="Automatik.EO_Automatik_aus_DOWN" Destination="Schneidwerk.S_OFF" Comment="" dx1="2106.666666666667" dx2="2106.666666666667" dy="0.0"/>
			<Connection Source="INIT" Destination="Heckschieber.INIT" Comment="" dx1="3800.0" dx2="3800.0" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Automatik.EO_Automatik_ein_UP" Destination="Heckschieber.OPEN" Comment="" dx1="2000.0" dx2="2000.0" dy="0.0"/>
			<Connection Source="Automatik.EO_Automatik_aus_DOWN" Destination="Heckschieber.CLOSE" Comment="" dx1="1893.3333333333335" dx2="1893.3333333333335" dy="0.0"/>
			<Connection Source="Heckschieber.CNF_2b" Destination="Vorsteuerventil_2B.REQ4" Comment="" dx1="80.0" dx2="80.0" dy="-1666.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Heckschieber.EO_Heckschieber_END" Destination="Automatik.CNF_Schieber" Comment="" dx1="660.0" dx2="660.0" dy="620.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="Automatik.Q_Verteiler_heben" Destination="Verteiler.IN_heben" Comment="" dx1="2060.0" dx2="2060.0" dy="0.0"/>
			<Connection Source="Automatik.Q_Verteiler_senken" Destination="Verteiler.IN_senken" Comment="" dx1="2066.666666666667" dx2="2066.666666666667" dy="0.0"/>
			<Connection Source="Klappen.OUT_a" Destination="Vorsteuerventil_2A.IN1" Comment="" dx1="1720.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Verteiler.OUT_a" Destination="Vorsteuerventil_2A.IN3" Comment="" dx1="80.0" dx2="80.0" dy="-1126.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Dom.OUT" Destination="Vorsteuerventil_2A.IN4" Comment="" dx1="2193.3333333333335" dx2="2193.3333333333335" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Seitenschieber.OUT" Destination="Vorsteuerventil_2A.IN5" Comment="" dx1="2193.3333333333335" dx2="2193.3333333333335" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Klappen.OUT_b" Destination="Vorsteuerventil_2B.IN1" Comment="" dx1="1720.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Verteiler.OUT_b" Destination="Vorsteuerventil_2B.IN3" Comment="" dx1="80.0" dx2="80.0" dy="-820.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Knickdeichsel.OUT_b" Destination="Vorsteuerventil_2B.IN2" Comment="" dx1="1786.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Knickdeichsel.OUT_a" Destination="Vorsteuerventil_2A.IN2" Comment="" dx1="1786.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Abscheider.OUT" Destination="Vorsteuerventil_2B.IN5" Comment="" dx1="1700.0" dx2="1700.0" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="Heckschieber.OUT_2b" Destination="Vorsteuerventil_2B.IN4" Comment="" dx1="80.0" dx2="80.0" dy="-1566.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
