<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Abscheider" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="Service Initialization">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF_2b" Type="Event" Comment="Execution Confirmation">
			</SubAppEvent>
		</SubAppEventOutputs>
		<OutputVars>
			<VarDeclaration Name="OUT_2b" Type="BOOL" Comment=""/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_IMPULSE_Abscheider" Type="E_IMPULSE" Comment="" x="3273.3333333333335" y="93.33333333333334">
			<Parameter Name="TM" Value="T#3s"/>
		</FB>
		<FB Name="E_T_FF_Abscheider" Type="E_T_FF" Comment="" x="1620.0" y="1053.3333333333335">
		</FB>
		<FB Name="Abscheider_7B" Type="QX" Comment="" x="5033.333333333334" y="0.0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AND_2_Abscheider" Type="AND_2" Comment="" x="5033.333333333334" y="953.3333333333334">
		</FB>
		<FB Name="GreenWhiteBackground_Abscheider" Type="GreenWhiteBackground" Comment="" x="3220.0" y="1720.0">
			<Parameter Name="u16ObjId" Value="5015"/>
		</FB>
		<FB Name="SoftKey_Abscheider_UP" Type="IE" Comment="" x="420.0" y="920.0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="E_T_FF_Abscheider.EO" Destination="E_IMPULSE_Abscheider.REQ" Comment="" dx1="393.33333333333337"/>
			<Connection Source="E_IMPULSE_Abscheider.CNF" Destination="AND_2_Abscheider.REQ" Comment="" dx1="393.33333333333337"/>
			<Connection Source="E_IMPULSE_Abscheider.CNF" Destination="Abscheider_7B.REQ" Comment="" dx1="473.33333333333337"/>
			<Connection Source="E_T_FF_Abscheider.EO" Destination="AND_2_Abscheider.REQ" Comment="" dx1="393.33333333333337"/>
			<Connection Source="E_T_FF_Abscheider.EO" Destination="GreenWhiteBackground_Abscheider.REQ" Comment="" dx1="393.33333333333337"/>
			<Connection Source="AND_2_Abscheider.CNF" Destination="CNF_2b" Comment="" dx1="213.33333333333334"/>
			<Connection Source="INIT" Destination="GreenWhiteBackground_Abscheider.INIT" Comment="" dx1="66.66666666666667"/>
			<Connection Source="INIT" Destination="Abscheider_7B.INIT" Comment="" dx1="4673.333333333334"/>
			<Connection Source="INIT" Destination="SoftKey_Abscheider_UP.INIT" Comment="" dx1="73.33333333333334" dx2="73.33333333333334" dy="0.0"/>
			<Connection Source="SoftKey_Abscheider_UP.IND" Destination="E_T_FF_Abscheider.CLK" Comment="" dx1="393.33333333333337" dx2="393.33333333333337" dy="0.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_IMPULSE_Abscheider.QO" Destination="AND_2_Abscheider.IN1" Comment="" dx1="333.33333333333337"/>
			<Connection Source="E_IMPULSE_Abscheider.QO" Destination="Abscheider_7B.OUT" Comment="" dx1="333.33333333333337"/>
			<Connection Source="E_T_FF_Abscheider.Q" Destination="AND_2_Abscheider.IN2" Comment="" dx1="1413.3333333333335"/>
			<Connection Source="E_T_FF_Abscheider.Q" Destination="GreenWhiteBackground_Abscheider.DI1" Comment="" dx1="106.66666666666667"/>
			<Connection Source="AND_2_Abscheider.OUT" Destination="OUT_2b" Comment="" dx1="260.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
