<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Softkeys" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="INITO" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventOutputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="UT_SoftkeyMapping" Type="UT_SoftkeyMapping" Comment="" x="1400.0" y="0.0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="255"/>
			<Parameter Name="u16ObjId_1" Value="5003"/>
			<Parameter Name="DigitalInput_1" Value="&quot;SoftKey_Auseinanderklappen&quot;"/>
			<Parameter Name="u16ObjId_2" Value="5004"/>
			<Parameter Name="DigitalInput_2" Value="&quot;SoftKey_Verteiler_senken&quot;"/>
			<Parameter Name="u16ObjId_3" Value="5005"/>
			<Parameter Name="DigitalInput_3" Value="&quot;SoftKey_Knickdeichsel_senken&quot;"/>
			<Parameter Name="u16ObjId_4" Value="5009"/>
			<Parameter Name="DigitalInput_4" Value="&quot;SoftKey_Zusammenklappen&quot;"/>
			<Parameter Name="u16ObjId_5" Value="5010"/>
			<Parameter Name="DigitalInput_5" Value="&quot;SoftKey_Verteiler_heben&quot;"/>
			<Parameter Name="u16ObjId_6" Value="5011"/>
			<Parameter Name="DigitalInput_6" Value="&quot;SoftKey_Knickdeichsel_heben&quot;"/>
		</FB>
		<FB Name="UT_SoftkeyMapping_UP" Type="UT_SoftkeyMapping_UP" Comment="" x="4400.0" y="0.0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="255"/>
			<Parameter Name="u16ObjId_1" Value="5000"/>
			<Parameter Name="DigitalInput_1" Value="&quot;SoftKey_Automatik_ein_UP&quot;"/>
			<Parameter Name="u16ObjId_2" Value="5001"/>
			<Parameter Name="DigitalInput_2" Value="&quot;SoftKey_Dom_UP&quot;"/>
			<Parameter Name="u16ObjId_3" Value="5002"/>
			<Parameter Name="DigitalInput_3" Value="&quot;SoftKey_Heckschieber_UP&quot;"/>
			<Parameter Name="u16ObjId_4" Value="5006"/>
			<Parameter Name="DigitalInput_4" Value="&quot;SoftKey_Automatik_aus_UP&quot;"/>
			<Parameter Name="u16ObjId_5" Value="5007"/>
			<Parameter Name="DigitalInput_5" Value="&quot;SoftKey_Schneidwerk_UP&quot;"/>
			<Parameter Name="u16ObjId_6" Value="5008"/>
			<Parameter Name="DigitalInput_6" Value="&quot;SoftKey_Seitenschieber_UP&quot;"/>
			<Parameter Name="u16ObjId_7" Value="5015"/>
			<Parameter Name="DigitalInput_7" Value="&quot;SoftKey_Abscheider_UP&quot;"/>
			<Parameter Name="u16ObjId_8" Value="5016"/>
			<Parameter Name="DigitalInput_8" Value="&quot;SoftKey_Licht_UP&quot;"/>
		</FB>
		<FB Name="UT_SoftkeyMapping_DOWN" Type="UT_SoftkeyMapping_DOWN" Comment="" x="7333.333333333334" y="60.0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="255"/>
			<Parameter Name="u16ObjId_1" Value="5000"/>
			<Parameter Name="DigitalInput_1" Value="&quot;SoftKey_Automatik_ein_DOWN&quot;"/>
			<Parameter Name="u16ObjId_7" Value="5006"/>
			<Parameter Name="DigitalInput_7" Value="&quot;SoftKey_Automatik_aus_DOWN&quot;"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="UT_SoftkeyMapping.INIT" Comment="" dx1="66.66666666666667" dx2="66.66666666666667" dy="73.33333333333334"/>
			<Connection Source="UT_SoftkeyMapping.INITO" Destination="UT_SoftkeyMapping_UP.INIT" Comment=""/>
			<Connection Source="UT_SoftkeyMapping_UP.INITO" Destination="UT_SoftkeyMapping_DOWN.INIT" Comment="" dx1="453.33333333333337" dx2="453.33333333333337" dy="0.0"/>
			<Connection Source="UT_SoftkeyMapping_DOWN.INITO" Destination="INITO" Comment="" dx1="66.66666666666667" dx2="66.66666666666667" dy="-106.66666666666667"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
