<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Seitenschieber" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF_2a" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventOutputs>
		<OutputVars>
			<VarDeclaration Name="OUT_2a" Type="BOOL" Comment=""/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="GreenWhiteBackground_Seitenschieber" Type="GreenWhiteBackground" Comment="" x="3580.0" y="13.333333333333334">
			<Parameter Name="u16ObjId" Value="5008"/>
		</FB>
		<FB Name="E_IMPULSE_Seitenschieber" Type="E_IMPULSE" Comment="" x="4026.666666666667" y="953.3333333333334">
			<Parameter Name="TM" Value="T#3s"/>
		</FB>
		<FB Name="AND_2_Seitenschieber" Type="AND_2" Comment="" x="5900.0" y="953.3333333333334">
		</FB>
		<FB Name="E_T_FF_Seitenschieber" Type="E_T_FF" Comment="" x="1773.3333333333335" y="1066.6666666666667">
		</FB>
		<FB Name="Seitenschieber_7A" Type="QX" Comment="" x="6100.0" y="0.0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="SoftKey_Seitenschieber_UP" Type="IE" Comment="" x="26.666666666666668" y="853.3333333333334">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="E_T_FF_Seitenschieber.EO" Destination="GreenWhiteBackground_Seitenschieber.REQ" Comment="" dx1="660.0"/>
			<Connection Source="GreenWhiteBackground_Seitenschieber.INITO" Destination="Seitenschieber_7A.INIT" Comment="" dx1="533.3333333333334"/>
			<Connection Source="E_T_FF_Seitenschieber.EO" Destination="E_IMPULSE_Seitenschieber.REQ" Comment="" dx1="660.0"/>
			<Connection Source="E_IMPULSE_Seitenschieber.CNF" Destination="Seitenschieber_7A.REQ" Comment="" dx1="640.0"/>
			<Connection Source="E_IMPULSE_Seitenschieber.CNF" Destination="AND_2_Seitenschieber.REQ" Comment=""/>
			<Connection Source="AND_2_Seitenschieber.CNF" Destination="CNF_2a" Comment="" dx1="633.3333333333334" dx2="360.0" dy="-553.3333333333334"/>
			<Connection Source="INIT" Destination="GreenWhiteBackground_Seitenschieber.INIT" Comment="" dx1="1900.0"/>
			<Connection Source="INIT" Destination="SoftKey_Seitenschieber_UP.INIT" Comment="" dx1="120.0" dx2="120.0" dy="0.0"/>
			<Connection Source="SoftKey_Seitenschieber_UP.IND" Destination="E_T_FF_Seitenschieber.CLK" Comment="" dx1="500.0" dx2="500.0" dy="0.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF_Seitenschieber.Q" Destination="GreenWhiteBackground_Seitenschieber.DI1" Comment="" dx1="600.0"/>
			<Connection Source="E_IMPULSE_Seitenschieber.QO" Destination="AND_2_Seitenschieber.IN1" Comment="" dx1="700.0"/>
			<Connection Source="E_IMPULSE_Seitenschieber.QO" Destination="Seitenschieber_7A.OUT" Comment="" dx1="700.0"/>
			<Connection Source="E_T_FF_Seitenschieber.Q" Destination="AND_2_Seitenschieber.IN2" Comment="" dx1="3040.0"/>
			<Connection Source="AND_2_Seitenschieber.OUT" Destination="OUT_2a" Comment="" dx1="1046.6666666666667" dx2="66.66666666666667" dy="-613.3333333333334"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
