<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="PAGE" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-07">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event">
				<Attribute Name="YPOSITION" Type="INT" Value="210"/>
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="IND" Type="Event">
				<Attribute Name="YPOSITION" Type="INT" Value="255"/>
			</SubAppEvent>
		</SubAppEventOutputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="BTN" Type="IE" x="0" y="0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AUX" Type="IE" x="0" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="BTN.INIT" dx1="600" dx2="600" dy="0"/>
			<Connection Source="INIT" Destination="AUX.INIT" dx1="600" dx2="600" dy="0"/>
			<Connection Source="AUX.IND" Destination="IND" dx1="2673.33"/>
			<Connection Source="BTN.IND" Destination="IND" dx1="2673.33"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
