<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="PAGES" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-06">
	</VersionInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Q_SoftKeyMask" Type="Q_SoftKeyMask" x="5600" y="-1200">
			<Parameter Name="u8MaskType" Value="1"/>
			<Parameter Name="u16DataMaskId" Value="DefaultPool::DataMask_1000"/>
		</FB>
		<SubApp Name="VT_active" Type="VT_active" x="-800" y="-1100">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<FB Name="F_SEL_I" Type="F_SEL_E_2" x="3400" y="-1100">
			<Parameter Name="IN0" Value="DefaultPool::SoftKeyMask_PAGE_1"/>
			<Parameter Name="IN1" Value="DefaultPool::SoftKeyMask_PAGE_2"/>
		</FB>
		<FB Name="E_SR_PAGE_1" Type="E_SR" x="3600" y="500">
		</FB>
		<FB Name="E_SR_PAGE_2" Type="E_SR" x="3500" y="2500">
		</FB>
		<SubApp Name="GreenWhiteBackground_PAGE_2" Type="GreenWhiteBackground" x="5100" y="2500">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Parameter Name="u16ObjId" Value="DefaultPool::PAGE_2_BTN"/>
			<Parameter Name="u16ObjIdA" Value="DefaultPool::PAGE_2_AUX"/>
		</SubApp>
		<SubApp Name="GreenWhiteBackground_PAGE_1" Type="GreenWhiteBackground" x="5100" y="500">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Parameter Name="u16ObjId" Value="DefaultPool::PAGE_1_BTN"/>
			<Parameter Name="u16ObjIdA" Value="DefaultPool::PAGE_1_AUX"/>
		</SubApp>
		<SubApp Name="PAGE_1" Type="PAGE" x="0" y="0">
		</SubApp>
		<SubApp Name="PAGE_2" Type="PAGE" x="0" y="533.33">
		</SubApp>
		<EventConnections>
			<Connection Source="F_SEL_I.CNF" Destination="Q_SoftKeyMask.REQ"/>
			<Connection Source="VT_active.EO" Destination="F_SEL_I.REQ0"/>
			<Connection Source="VT_active.EO" Destination="E_SR_PAGE_1.S" dx1="1860">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="VT_active.EO" Destination="E_SR_PAGE_2.R" dx1="1806.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_SR_PAGE_2.EO" Destination="GreenWhiteBackground_PAGE_2.REQ"/>
			<Connection Source="E_SR_PAGE_1.EO" Destination="GreenWhiteBackground_PAGE_1.REQ"/>
			<Connection Source="PAGE_1.IND" Destination="F_SEL_I.REQ0" dx1="1033.33"/>
			<Connection Source="PAGE_1.IND" Destination="E_SR_PAGE_1.S" dx1="1526.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="PAGE_1.IND" Destination="E_SR_PAGE_2.R" dx1="1480">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="PAGE_2.IND" Destination="F_SEL_I.REQ1" dx1="1326.67"/>
			<Connection Source="PAGE_2.IND" Destination="E_SR_PAGE_2.S" dx1="1480">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="PAGE_2.IND" Destination="E_SR_PAGE_1.R" dx1="1526.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
		<DataConnections>
			<Connection Source="F_SEL_I.OUT" Destination="Q_SoftKeyMask.u16SoftKeyMaskId" dx1="180"/>
			<Connection Source="E_SR_PAGE_2.Q" Destination="GreenWhiteBackground_PAGE_2.DI1" dx1="566.67"/>
			<Connection Source="E_SR_PAGE_1.Q" Destination="GreenWhiteBackground_PAGE_1.DI1" dx1="513.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
