<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="VT_active" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-19">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventOutputs>
			<SubAppEvent Name="EO" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_D_FF" Type="E_D_FF" x="1100" y="300">
		</FB>
		<FB Name="CbVtStatus" Type="CbVtStatus" x="0" y="0">
		</FB>
		<EventConnections>
			<Connection Source="CbVtStatus.IND" Destination="E_D_FF.CLK" dx1="126.67"/>
			<Connection Source="E_D_FF.EO" Destination="EO" dx1="2740"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="CbVtStatus.qWsActive" Destination="E_D_FF.D"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
