<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="AuxInput_Dom_UP" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-06">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="IND" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventOutputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_SWITCH_AuxInput_Dom" Type="E_SWITCH" Comment="" x="1300.0" y="200.0">
		</FB>
		<FB Name="AuxInput_Dom" Type="IX" Comment="" x="0.0" y="100.0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="AuxInput_Dom.IND" Destination="E_SWITCH_AuxInput_Dom.EI" Comment=""/>
			<Connection Source="INIT" Destination="AuxInput_Dom.INIT" Comment="" dx1="633.3333333333334"/>
			<Connection Source="E_SWITCH_AuxInput_Dom.EO0" Destination="IND" Comment="" dx1="713.3333333333334"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="AuxInput_Dom.IN" Destination="E_SWITCH_AuxInput_Dom.G" Comment="" dx1="546.6666666666667"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
