<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GreenWhiteBackground_Dom" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-06">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="20"/>
			</SubAppEvent>
			<SubAppEvent Name="EO" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="272"/>
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="Q" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="139"/>
			</VarDeclaration>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="GreenWhiteBackground_SoftKey_Dom" Type="GreenWhiteBackground" Comment="" x="-2400.0" y="-3466.666666666667">
			<Parameter Name="u16ObjId" Value="5001"/>
		</FB>
		<FB Name="GreenWhiteBackground_AUX_Dom" Type="GreenWhiteBackground" Comment="" x="-2400.0" y="-2526.666666666667">
			<Parameter Name="u16ObjId" Value="31001"/>
		</FB>
		<FB Name="GreenWhiteBackground_AUX_Dom_Joystick" Type="GreenWhiteBackgroundAux" Comment="" x="-2400.0" y="-1620.0">
			<Parameter Name="u16ObjId" Value="31001"/>
		</FB>
		<EventConnections>
			<Connection Source="EO" Destination="GreenWhiteBackground_SoftKey_Dom.REQ" Comment="" dx1="573.3333333333334"/>
			<Connection Source="INIT" Destination="GreenWhiteBackground_SoftKey_Dom.INIT" Comment="" dx1="766.6666666666667"/>
			<Connection Source="EO" Destination="GreenWhiteBackground_AUX_Dom.REQ" Comment="" dx1="786.6666666666667"/>
			<Connection Source="INIT" Destination="GreenWhiteBackground_AUX_Dom.INIT" Comment="" dx1="466.6666666666667"/>
			<Connection Source="INIT" Destination="GreenWhiteBackground_AUX_Dom_Joystick.INIT" Comment="" dx1="360.0"/>
			<Connection Source="EO" Destination="GreenWhiteBackground_AUX_Dom_Joystick.REQ" Comment="" dx1="253.33333333333334"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="Q" Destination="GreenWhiteBackground_SoftKey_Dom.DI1" Comment="" dx1="680.0"/>
			<Connection Source="Q" Destination="GreenWhiteBackground_AUX_Dom.DI1" Comment="" dx1="893.3333333333334"/>
			<Connection Source="Q" Destination="GreenWhiteBackground_AUX_Dom_Joystick.DI1" Comment="" dx1="1000.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
