<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="IN" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-11">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventOutputs>
			<SubAppEvent Name="IND" Type="Event">
				<Attribute Name="YPOSITION" Type="INT" Value="20"/>
			</SubAppEvent>
		</SubAppEventOutputs>
		<OutputVars>
			<VarDeclaration Name="IN" Type="BOOL">
				<Attribute Name="YPOSITION" Type="INT" Value="134"/>
			</VarDeclaration>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="IX" Type="IX" x="-846.67" y="-900">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="IX.IND" Destination="IND" dx1="533.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="IX.IN" Destination="IN" dx1="893.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
