<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="doppeltwirkend" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="EI_heben" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="EI_senken" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF_b" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="CNF_a" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="IN_heben" Type="BOOL" Comment=""/>
			<VarDeclaration Name="IN_senken" Type="BOOL" Comment=""/>
			<VarDeclaration Name="u16ObjId_heben" Type="UINT" Comment=""/>
			<VarDeclaration Name="u16ObjId_senken" Type="UINT" Comment=""/>
			<VarDeclaration Name="u16ObjIdA_heben" Type="UINT" Comment=""/>
			<VarDeclaration Name="u16ObjIdA_senken" Type="UINT" Comment=""/>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="OUT_b" Type="BOOL" Comment=""/>
			<VarDeclaration Name="OUT_a" Type="BOOL" Comment=""/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="OR_2_heben" Type="OR_3" Comment="" x="3166.666666666667" y="766.6666666666667">
		</FB>
		<FB Name="OR_2_senken" Type="OR_3" Comment="" x="3066.666666666667" y="2166.666666666667">
		</FB>
		<SubApp Name="SoftKey_heben" Type="SoftKey" Comment="" x="666.6666666666667" y="566.6666666666667">
		</SubApp>
		<SubApp Name="SoftKey_senken" Type="SoftKey" Comment="" x="666.6666666666667" y="1566.6666666666667">
		</SubApp>
		<SubApp Name="GreenWhiteBackground_heben" Type="GreenWhiteBackground_Function" Comment="" x="5933.333333333334" y="3533.3333333333335">
		</SubApp>
		<SubApp Name="GreenWhiteBackground_senken" Type="GreenWhiteBackground_Function" Comment="" x="5933.333333333334" y="4466.666666666667">
		</SubApp>
		<SubApp Name="AuxInput_heben" Type="AuxInput" Comment="" x="666.6666666666667" y="1066.6666666666667">
		</SubApp>
		<SubApp Name="AuxInput_senken" Type="AuxInput" Comment="" x="666.6666666666667" y="2066.666666666667">
		</SubApp>
		<SubApp Name="Sitzventile" Type="Sitzventile" Comment="" x="6793.333333333334" y="2586.666666666667">
		</SubApp>
		<EventConnections>
			<Connection Source="EI_heben" Destination="OR_2_heben.REQ" Comment="" dx1="3566.666666666667"/>
			<Connection Source="OR_2_heben.CNF" Destination="CNF_a" Comment="" dx1="5406.666666666667"/>
			<Connection Source="EI_senken" Destination="OR_2_senken.REQ" Comment="" dx1="3406.666666666667"/>
			<Connection Source="OR_2_senken.CNF" Destination="CNF_b" Comment="" dx1="5333.333333333334"/>
			<Connection Source="INIT" Destination="SoftKey_heben.INIT" Comment="" dx1="1000.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="SoftKey_heben.IND" Destination="OR_2_heben.REQ" Comment="" dx1="940.0"/>
			<Connection Source="INIT" Destination="SoftKey_senken.INIT" Comment="" dx1="1006.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="SoftKey_senken.IND" Destination="OR_2_senken.REQ" Comment="" dx1="893.3333333333334"/>
			<Connection Source="INIT" Destination="GreenWhiteBackground_heben.INIT" Comment="" dx1="2733.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="OR_2_heben.CNF" Destination="GreenWhiteBackground_heben.EO" Comment="" dx1="680.0"/>
			<Connection Source="INIT" Destination="GreenWhiteBackground_senken.INIT" Comment="" dx1="3200.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="OR_2_senken.CNF" Destination="GreenWhiteBackground_senken.EO" Comment="" dx1="1186.6666666666667"/>
			<Connection Source="INIT" Destination="AuxInput_heben.INIT" Comment="" dx1="1000.0" dx2="1000.0" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="AuxInput_heben.IND" Destination="OR_2_heben.REQ" Comment="" dx1="546.6666666666667" dx2="546.6666666666667" dy="0.0"/>
			<Connection Source="INIT" Destination="AuxInput_senken.INIT" Comment="" dx1="1000.0" dx2="1000.0" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="AuxInput_senken.IND" Destination="OR_2_senken.REQ" Comment="" dx1="600.0" dx2="600.0" dy="0.0"/>
			<Connection Source="INIT" Destination="Sitzventile.INITO" Comment="" dx1="4060.0" dx2="4060.0" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="OR_2_heben.CNF" Destination="Sitzventile.CNF_heben" Comment="" dx1="1553.3333333333335" dx2="1553.3333333333335" dy="0.0"/>
			<Connection Source="OR_2_senken.CNF" Destination="Sitzventile.CNF_senken" Comment="" dx1="1580.0" dx2="1580.0" dy="0.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="IN_heben" Destination="OR_2_heben.IN2" Comment="" dx1="3246.666666666667"/>
			<Connection Source="OR_2_heben.OUT" Destination="OUT_a" Comment="" dx1="5593.333333333334"/>
			<Connection Source="IN_senken" Destination="OR_2_senken.IN2" Comment="" dx1="173.33333333333334"/>
			<Connection Source="OR_2_senken.OUT" Destination="OUT_b" Comment="" dx1="5606.666666666667"/>
			<Connection Source="SoftKey_heben.IN" Destination="OR_2_heben.IN1" Comment="" dx1="940.0"/>
			<Connection Source="SoftKey_senken.IN" Destination="OR_2_senken.IN1" Comment="" dx1="893.3333333333334"/>
			<Connection Source="OR_2_heben.OUT" Destination="GreenWhiteBackground_heben.Q" Comment="" dx1="680.0"/>
			<Connection Source="OR_2_senken.OUT" Destination="GreenWhiteBackground_senken.Q" Comment="" dx1="1186.6666666666667"/>
			<Connection Source="u16ObjId_heben" Destination="GreenWhiteBackground_heben.u16ObjId" Comment="" dx1="2733.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="u16ObjId_senken" Destination="GreenWhiteBackground_senken.u16ObjId" Comment="" dx1="2733.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="u16ObjIdA_heben" Destination="GreenWhiteBackground_heben.u16ObjIdA" Comment="" dx1="2733.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="u16ObjIdA_senken" Destination="GreenWhiteBackground_senken.u16ObjIdA" Comment="" dx1="2733.3333333333335">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="AuxInput_heben.IN" Destination="OR_2_heben.IN3" Comment="" dx1="546.6666666666667" dx2="546.6666666666667" dy="0.0"/>
			<Connection Source="AuxInput_senken.IN" Destination="OR_2_senken.IN3" Comment="" dx1="246.66666666666669" dx2="246.66666666666669" dy="0.0"/>
			<Connection Source="OR_2_heben.OUT" Destination="Sitzventile.IN_heben" Comment="" dx1="1533.3333333333335" dx2="1533.3333333333335" dy="0.0"/>
			<Connection Source="OR_2_senken.OUT" Destination="Sitzventile.IN_senken" Comment="" dx1="1580.0" dx2="1580.0" dy="0.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
