<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Automatik" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="CNF_Schieber" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="EO_Verteiler_heben" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="EO_Verteiler_senken" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="EO_Automatik_ein" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="EO_Automatik_ein_UP" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="EO_Automatik_aus_DOWN" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
		<OutputVars>
			<VarDeclaration Name="Q_Verteiler_heben" Type="BOOL"/>
			<VarDeclaration Name="Q_Verteiler_senken" Type="BOOL"/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_SR_Verteiler_heben" Type="E_SR" x="4800" y="3993.33">
		</FB>
		<FB Name="E_SR_Verteiler_senken" Type="E_SR" x="2266.67" y="933.33">
		</FB>
		<FB Name="E_REND_Automatik_ein" Type="E_REND" x="4246.67" y="1593.33">
		</FB>
		<FB Name="E_FWD_DLY_Automatik_ein_UP" Type="E_DELAY" x="1853.33" y="1593.33">
			<Parameter Name="DT" Value="T#10ms"/>
		</FB>
		<FB Name="E_FWD_DLY_Automatik_aus_DOWN" Type="E_DELAY" x="2393.33" y="2446.67">
			<Parameter Name="DT" Value="T#10ms"/>
		</FB>
		<SubApp Name="ein" Type="ein" x="-500" y="500">
		</SubApp>
		<SubApp Name="aus" Type="ein" x="-600" y="2600">
		</SubApp>
		<EventConnections>
			<Connection Source="E_SR_Verteiler_heben.EO" Destination="EO_Verteiler_heben" dx1="140"/>
			<Connection Source="E_SR_Verteiler_senken.EO" Destination="EO_Verteiler_senken" dx1="2760"/>
			<Connection Source="CNF_Schieber" Destination="E_REND_Automatik_ein.EI1" dx1="5440"/>
			<Connection Source="E_REND_Automatik_ein.EO" Destination="EO_Automatik_ein" dx1="1013.33"/>
			<Connection Source="E_FWD_DLY_Automatik_ein_UP.EO" Destination="E_REND_Automatik_ein.EI2" dx1="713.33"/>
			<Connection Source="E_FWD_DLY_Automatik_aus_DOWN.EO" Destination="E_SR_Verteiler_heben.S" dx1="840"/>
			<Connection Source="ein.DOWN" Destination="E_SR_Verteiler_senken.S" dx1="1260"/>
			<Connection Source="ein.UP" Destination="E_FWD_DLY_Automatik_ein_UP.START" dx1="1053.33"/>
			<Connection Source="ein.UP" Destination="E_SR_Verteiler_senken.R" dx1="1300"/>
			<Connection Source="ein.UP" Destination="E_REND_Automatik_ein.R" dx1="3446.67"/>
			<Connection Source="ein.UP" Destination="EO_Automatik_ein_UP" dx1="3120"/>
			<Connection Source="aus.UP" Destination="E_SR_Verteiler_heben.R" dx1="2320"/>
			<Connection Source="aus.DOWN" Destination="E_FWD_DLY_Automatik_aus_DOWN.START" dx1="1393.33"/>
			<Connection Source="aus.DOWN" Destination="EO_Automatik_aus_DOWN" dx1="1640"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR_Verteiler_heben.Q" Destination="Q_Verteiler_heben" dx1="46.67" dx2="246.67" dy="-860"/>
			<Connection Source="E_SR_Verteiler_senken.Q" Destination="Q_Verteiler_senken" dx1="1826.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
