<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="ein" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-07">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventOutputs>
			<SubAppEvent Name="UP" Type="Event">
				<Attribute Name="YPOSITION" Type="INT" Value="255"/>
			</SubAppEvent>
			<SubAppEvent Name="DOWN" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey" Type="IX" x="-200" y="0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AuxInput" Type="IX" x="-200" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="OR_2" Type="OR_2" x="1800" y="300">
		</FB>
		<FB Name="E_SWITCH" Type="E_SWITCH" x="3066.67" y="266.67">
		</FB>
		<EventConnections>
			<Connection Source="SoftKey.IND" Destination="OR_2.REQ" dx1="500"/>
			<Connection Source="AuxInput.IND" Destination="OR_2.REQ" dx1="500"/>
			<Connection Source="OR_2.CNF" Destination="E_SWITCH.EI" dx1="220"/>
			<Connection Source="E_SWITCH.EO0" Destination="UP" dx1="1926.67"/>
			<Connection Source="E_SWITCH.EO1" Destination="DOWN" dx1="133.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="SoftKey.IN" Destination="OR_2.IN1" dx1="673.33"/>
			<Connection Source="AuxInput.IN" Destination="OR_2.IN2" dx1="600"/>
			<Connection Source="OR_2.OUT" Destination="E_SWITCH.G" dx1="220"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
