<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Klappen" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="46"/>
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF_2b" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="138"/>
			</SubAppEvent>
			<SubAppEvent Name="CNF_2a" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="300"/>
			</SubAppEvent>
		</SubAppEventOutputs>
		<OutputVars>
			<VarDeclaration Name="OUT_2b" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="0"/>
			</VarDeclaration>
			<VarDeclaration Name="OUT_2a" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="0"/>
			</VarDeclaration>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_Auseinanderklappen" Type="IX" Comment="" x="353.33333333333337" y="40.0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="GreenWhiteBackground_Auseinanderklappen" Type="GreenWhiteBackground" Comment="" x="3220.0" y="2800.0">
			<Parameter Name="u16ObjId" Value="5003"/>
		</FB>
		<FB Name="SoftKey_Zusammenklappen" Type="IX" Comment="" x="553.3333333333334" y="1053.3333333333335">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<SubApp Name="Sitzventile" Comment="Sitzventile" x="5220.0" y="1853.3333333333335">
			<SubAppInterfaceList>
				<SubAppEventInputs>
					<SubAppEvent Name="INIT" Type="Event" Comment="">
					</SubAppEvent>
					<SubAppEvent Name="IND_Auseinanderklappen" Type="Event" Comment="">
					</SubAppEvent>
					<SubAppEvent Name="IND_Zusammenklappen" Type="Event" Comment="">
					</SubAppEvent>
				</SubAppEventInputs>
				<InputVars>
					<VarDeclaration Name="IN_Auseinanderklappen" Type="BOOL" Comment=""/>
					<VarDeclaration Name="IN_Zusammenklappen" Type="BOOL" Comment=""/>
				</InputVars>
			</SubAppInterfaceList>
			<SubAppNetwork>
				<FB Name="Klappen_3B" Type="QX" Comment="" x="1680.0" y="973.3333333333334">
					<Parameter Name="QI" Value="TRUE"/>
				</FB>
				<FB Name="Klappen_3A" Type="QX" Comment="" x="1600.0" y="0.0">
					<Parameter Name="QI" Value="TRUE"/>
				</FB>
				<FB Name="OR_3A_3B" Type="OR_2" Comment="" x="613.3333333333334" y="440.0">
					<Attribute Name="PinComment" Type="STRING" Value="IN1:Auseinanderklappen"/>
					<Attribute Name="PinComment" Type="STRING" Value="IN2:Zusammenklappen"/>
				</FB>
				<EventConnections>
					<Connection Source="OR_3A_3B.CNF" Destination="Klappen_3B.REQ" Comment="" dx1="113.33333333333334"/>
					<Connection Source="OR_3A_3B.CNF" Destination="Klappen_3A.REQ" Comment="" dx1="453.33333333333337"/>
					<Connection Source="INIT" Destination="Klappen_3B.INIT" Comment="" dx1="1826.6666666666667"/>
					<Connection Source="INIT" Destination="Klappen_3A.INIT" Comment="" dx1="1826.6666666666667"/>
					<Connection Source="IND_Auseinanderklappen" Destination="OR_3A_3B.REQ" Comment="" dx1="506.6666666666667"/>
					<Connection Source="IND_Zusammenklappen" Destination="OR_3A_3B.REQ" Comment="" dx1="466.6666666666667"/>
				</EventConnections>
				<DataConnections>
					<Connection Source="OR_3A_3B.OUT" Destination="Klappen_3B.OUT" Comment="" dx1="480.0"/>
					<Connection Source="OR_3A_3B.OUT" Destination="Klappen_3A.OUT" Comment="" dx1="453.33333333333337"/>
					<Connection Source="IN_Auseinanderklappen" Destination="OR_3A_3B.IN1" Comment="" dx1="260.0"/>
					<Connection Source="IN_Zusammenklappen" Destination="OR_3A_3B.IN2" Comment="" dx1="66.66666666666667"/>
				</DataConnections>
			</SubAppNetwork>
			<Attribute Name="Unfolded" Type="STRING" Value="true"/>
			<Attribute Name="width" Type="LREAL" Value="3893.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="2400.0"/>
		</SubApp>
		<FB Name="GreenWhiteBackground_Zusammenklappen" Type="GreenWhiteBackground" Comment="" x="3220.0" y="3720.0">
			<Parameter Name="u16ObjId" Value="5009"/>
		</FB>
		<EventConnections>
			<Connection Source="SoftKey_Auseinanderklappen.IND" Destination="GreenWhiteBackground_Auseinanderklappen.REQ" Comment="" dx1="1793.3333333333335"/>
			<Connection Source="INIT" Destination="SoftKey_Auseinanderklappen.INIT" Comment="" dx1="66.66666666666667"/>
			<Connection Source="SoftKey_Auseinanderklappen.IND" Destination="CNF_2b" Comment="" dx1="260.0"/>
			<Connection Source="INIT" Destination="SoftKey_Zusammenklappen.INIT" Comment="" dx1="66.66666666666667"/>
			<Connection Source="SoftKey_Zusammenklappen.IND" Destination="CNF_2a" Comment="" dx1="246.66666666666669"/>
			<Connection Source="INIT" Destination="GreenWhiteBackground_Auseinanderklappen.INIT" Comment="" dx1="66.66666666666667"/>
			<Connection Source="INIT" Destination="Sitzventile.INIT" Comment="" dx1="66.66666666666667"/>
			<Connection Source="SoftKey_Auseinanderklappen.IND" Destination="Sitzventile.IND_Auseinanderklappen" Comment="" dx1="3426.666666666667"/>
			<Connection Source="SoftKey_Zusammenklappen.IND" Destination="Sitzventile.IND_Zusammenklappen" Comment="" dx1="3106.666666666667"/>
			<Connection Source="SoftKey_Zusammenklappen.IND" Destination="GreenWhiteBackground_Zusammenklappen.REQ" Comment="" dx1="1446.6666666666667"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="SoftKey_Auseinanderklappen.IN" Destination="GreenWhiteBackground_Auseinanderklappen.DI1" Comment="" dx1="1673.3333333333335"/>
			<Connection Source="SoftKey_Auseinanderklappen.IN" Destination="OUT_2b" Comment="" dx1="480.0"/>
			<Connection Source="SoftKey_Zusammenklappen.IN" Destination="OUT_2a" Comment="" dx1="573.3333333333334"/>
			<Connection Source="SoftKey_Auseinanderklappen.IN" Destination="Sitzventile.IN_Auseinanderklappen" Comment="" dx1="3140.0"/>
			<Connection Source="SoftKey_Zusammenklappen.IN" Destination="Sitzventile.IN_Zusammenklappen" Comment="" dx1="2926.666666666667"/>
			<Connection Source="SoftKey_Zusammenklappen.IN" Destination="GreenWhiteBackground_Zusammenklappen.DI1" Comment="" dx1="1320.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
