<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Licht" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="Service Initialization">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_T_FF_Licht" Type="E_T_FF" Comment="" x="1520.0" y="193.33333333333334">
		</FB>
		<FB Name="GreenWhiteBackground_Licht" Type="GreenWhiteBackground" Comment="" x="4500.0" y="0.0">
			<Parameter Name="u16ObjId" Value="5016"/>
		</FB>
		<FB Name="Licht_8A" Type="QX" Comment="" x="2900.0" y="973.3333333333334">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="SoftKey_Licht_UP" Type="IE" Comment="" x="240.0" y="0.0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="E_T_FF_Licht.EO" Destination="Licht_8A.REQ" Comment="" dx1="126.66666666666667"/>
			<Connection Source="E_T_FF_Licht.EO" Destination="GreenWhiteBackground_Licht.REQ" Comment="" dx1="126.66666666666667"/>
			<Connection Source="INIT" Destination="SoftKey_Licht_UP.INIT" Comment="" dx1="66.66666666666667" dx2="66.66666666666667" dy="73.33333333333334"/>
			<Connection Source="SoftKey_Licht_UP.INITO" Destination="GreenWhiteBackground_Licht.INIT" Comment=""/>
			<Connection Source="SoftKey_Licht_UP.INITO" Destination="Licht_8A.INIT" Comment="" dx1="113.33333333333334" dx2="113.33333333333334" dy="0.0"/>
			<Connection Source="SoftKey_Licht_UP.IND" Destination="E_T_FF_Licht.CLK" Comment="" dx1="260.0" dx2="260.0" dy="0.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF_Licht.Q" Destination="Licht_8A.OUT" Comment="" dx1="60.0"/>
			<Connection Source="E_T_FF_Licht.Q" Destination="GreenWhiteBackground_Licht.DI1" Comment="" dx1="393.33333333333337"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
