<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Schneidwerk" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="S_ON" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="S_OFF" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Schneidwerk_rechtslauf_1A" Type="QX" Comment="" x="5033.333333333334" y="2713.3333333333335">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="GreenWhiteBackground_Schneidwerk" Type="GreenWhiteBackground" Comment="" x="4900.0" y="3646.666666666667">
			<Parameter Name="u16ObjId" Value="5007"/>
		</FB>
		<FB Name="E_SWITCH_Schneidwerk" Type="E_SWITCH" Comment="" x="1700.0" y="980.0">
		</FB>
		<FB Name="E_SR_Schneidwerk" Type="E_SR" Comment="" x="3300.0" y="980.0">
		</FB>
		<FB Name="Schneidwerk_linkslauf_1B" Type="QX" Comment="" x="5033.333333333334" y="1913.3333333333335">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="SoftKey_Schneidwerk_UP" Type="IE" Comment="" x="100.0" y="980.0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="E_SR_Schneidwerk.EO" Destination="Schneidwerk_rechtslauf_1A.REQ" Comment="" dx1="700.0"/>
			<Connection Source="E_SR_Schneidwerk.EO" Destination="GreenWhiteBackground_Schneidwerk.REQ" Comment="" dx1="700.0"/>
			<Connection Source="E_SWITCH_Schneidwerk.EO0" Destination="E_SR_Schneidwerk.S" Comment=""/>
			<Connection Source="E_SWITCH_Schneidwerk.EO1" Destination="E_SR_Schneidwerk.R" Comment=""/>
			<Connection Source="S_ON" Destination="E_SR_Schneidwerk.S" Comment="" dx1="2980.0"/>
			<Connection Source="S_OFF" Destination="E_SR_Schneidwerk.R" Comment="" dx1="3233.3333333333335"/>
			<Connection Source="INIT" Destination="Schneidwerk_linkslauf_1B.INIT" Comment="" dx1="66.66666666666667"/>
			<Connection Source="INIT" Destination="GreenWhiteBackground_Schneidwerk.INIT" Comment="" dx1="66.66666666666667"/>
			<Connection Source="INIT" Destination="Schneidwerk_rechtslauf_1A.INIT" Comment="" dx1="66.66666666666667"/>
			<Connection Source="INIT" Destination="SoftKey_Schneidwerk_UP.INIT" Comment="" dx1="66.66666666666667" dx2="66.66666666666667" dy="0.0"/>
			<Connection Source="SoftKey_Schneidwerk_UP.IND" Destination="E_SWITCH_Schneidwerk.EI" Comment="" dx1="493.33333333333337" dx2="493.33333333333337" dy="0.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR_Schneidwerk.Q" Destination="Schneidwerk_rechtslauf_1A.OUT" Comment="" dx1="393.33333333333337"/>
			<Connection Source="E_SR_Schneidwerk.Q" Destination="GreenWhiteBackground_Schneidwerk.DI1" Comment="" dx1="393.33333333333337"/>
			<Connection Source="E_SR_Schneidwerk.Q" Destination="E_SWITCH_Schneidwerk.G" Comment="" dx1="393.33333333333337" dx2="500.0" dy="300.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
