<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GreenWhiteBackground_Function" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-06">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event">
				<Attribute Name="YPOSITION" Type="INT" Value="20"/>
			</SubAppEvent>
			<SubAppEvent Name="EO" Type="Event">
				<Attribute Name="YPOSITION" Type="INT" Value="272"/>
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="Q" Type="BOOL">
				<Attribute Name="YPOSITION" Type="INT" Value="139"/>
			</VarDeclaration>
			<VarDeclaration Name="u16ObjId" Type="UINT"/>
			<VarDeclaration Name="u16ObjIdA" Type="UINT"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="GreenWhiteBackground" Type="GreenWhiteBackground" x="-2533.33" y="-3466.67">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<EventConnections>
			<Connection Source="EO" Destination="GreenWhiteBackground.REQ" dx1="573.33" dx2="573.33" dy="0"/>
			<Connection Source="INIT" Destination="GreenWhiteBackground.INIT" dx1="766.67" dx2="766.67" dy="0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="Q" Destination="GreenWhiteBackground.DI1" dx1="680" dx2="680" dy="0"/>
			<Connection Source="u16ObjId" Destination="GreenWhiteBackground.u16ObjId" dx1="733.33"/>
			<Connection Source="u16ObjIdA" Destination="GreenWhiteBackground.u16ObjIdA" dx1="833.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
