<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="IE_UP" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-06">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventOutputs>
			<SubAppEvent Name="IND" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="IE" Type="IE" x="0" y="100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="IE.IND" Destination="IND" dx1="1613.33"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
