<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="IN_UP" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-06">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventOutputs>
			<SubAppEvent Name="IND" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_SWITCH" Type="E_SWITCH" x="1466.67" y="400">
		</FB>
		<FB Name="IX" Type="IX" x="0" y="100">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="IX.IND" Destination="E_SWITCH.EI" dx1="386.67"/>
			<Connection Source="E_SWITCH.EO0" Destination="IND" dx1="713.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="IX.IN" Destination="E_SWITCH.G" dx1="546.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
