<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="TimedFunc" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="345"/>
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="u16ObjId" Type="UINT" Comment=""/>
			<VarDeclaration Name="u16ObjIdA" Type="UINT" Comment=""/>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="OUT" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="18"/>
			</VarDeclaration>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AND_2" Type="AND_2" Comment="" x="4800.0" y="900.0">
		</FB>
		<FB Name="E_T_FF" Type="E_T_FF" Comment="" x="1100.0" y="-700.0">
		</FB>
		<FB Name="QX" Type="QX" Comment="" x="4800.0" y="-100.0">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<FB Name="E_IMPULSE" Type="E_IMPULSE" Comment="" x="2666.666666666667" y="0.0">
			<Parameter Name="TM" Value="T#3s" Comment=""/>
		</FB>
		<SubApp Name="GreenWhiteBackground" Type="GreenWhiteBackground_Function" Comment="" x="2700.0" y="-800.0">
		</SubApp>
		<SubApp Name="AuxInput_UP" Type="AuxInput_UP" Comment="" x="-1066.6666666666667" y="-133.33333333333334">
		</SubApp>
		<SubApp Name="SoftKey_UP" Type="SoftKey_UP" Comment="" x="-1066.6666666666667" y="-666.6666666666667">
		</SubApp>
		<EventConnections>
			<Connection Source="E_IMPULSE.CNF" Destination="AND_2.REQ" Comment="" dx1="473.33333333333337"/>
			<Connection Source="E_T_FF.EO" Destination="E_IMPULSE.REQ" Comment="" dx1="520.0"/>
			<Connection Source="E_IMPULSE.CNF" Destination="QX.REQ" Comment=""/>
			<Connection Source="AND_2.CNF" Destination="CNF" Comment="" dx1="506.6666666666667"/>
			<Connection Source="INIT" Destination="QX.INIT" Comment="" dx1="6086.666666666667"/>
			<Connection Source="INIT" Destination="GreenWhiteBackground.INIT" Comment="" dx1="3960.0" dx2="3960.0" dy="0.0"/>
			<Connection Source="E_T_FF.EO" Destination="GreenWhiteBackground.EO" Comment=""/>
			<Connection Source="INIT" Destination="AuxInput_UP.INIT" Comment="" dx1="193.33333333333334" dx2="193.33333333333334" dy="0.0"/>
			<Connection Source="AuxInput_UP.IND" Destination="E_T_FF.CLK" Comment="" dx1="453.33333333333337" dx2="453.33333333333337" dy="0.0"/>
			<Connection Source="INIT" Destination="SoftKey_UP.INIT" Comment="" dx1="193.33333333333334" dx2="193.33333333333334" dy="0.0"/>
			<Connection Source="SoftKey_UP.IND" Destination="E_T_FF.CLK" Comment="" dx1="500.0" dx2="500.0" dy="0.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_IMPULSE.QO" Destination="AND_2.IN1" Comment="" dx1="366.6666666666667"/>
			<Connection Source="E_T_FF.Q" Destination="AND_2.IN2" Comment="Schieber offen" dx1="320.0"/>
			<Connection Source="E_IMPULSE.QO" Destination="QX.OUT" Comment="" dx1="580.0"/>
			<Connection Source="AND_2.OUT" Destination="OUT" Comment="" dx1="613.3333333333334"/>
			<Connection Source="E_T_FF.Q" Destination="GreenWhiteBackground.Q" Comment=""/>
			<Connection Source="u16ObjId" Destination="GreenWhiteBackground.u16ObjId" Comment="" dx1="2020.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="u16ObjIdA" Destination="GreenWhiteBackground.u16ObjIdA" Comment="" dx1="2020.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
