<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Softkeys" Comment="Mapping for all Softkey" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="UT_SoftkeyMapping" Type="UT_SoftkeyMapping" x="1066.67" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="isobus::GLOBAL"/>
			<Parameter Name="u16ObjId_1" Value="DefaultPool::SoftKey_Automatik_ein"/>
			<Parameter Name="u16ObjId_2" Value="DefaultPool::SoftKey_Auseinanderklappen"/>
			<Parameter Name="u16ObjId_3" Value="DefaultPool::SoftKey_Verteiler_senken"/>
			<Parameter Name="u16ObjId_4" Value="DefaultPool::SoftKey_Knickdeichsel_senken"/>
			<Parameter Name="DigitalInput_4" Value="'App.Control.functions.Knickdeichsel.SoftKey_senken.IX'"/>
			<Parameter Name="u16ObjId_5" Value="DefaultPool::SoftKey_Automatik_aus"/>
			<Parameter Name="DigitalInput_5" Value="'App.Control.functions.Automatik.aus.SoftKey'"/>
			<Parameter Name="u16ObjId_6" Value="DefaultPool::SoftKey_Zusammenklappen"/>
			<Parameter Name="DigitalInput_6" Value="'App.Control.functions.Klappen.SoftKey_senken.IX'"/>
			<Parameter Name="u16ObjId_7" Value="DefaultPool::SoftKey_Verteiler_heben"/>
			<Parameter Name="DigitalInput_7" Value="'App.Control.functions.Verteiler.SoftKey_heben.IX'"/>
			<Parameter Name="u16ObjId_8" Value="DefaultPool::SoftKey_Knickdeichsel_heben"/>
			<Parameter Name="DigitalInput_8" Value="'App.Control.functions.Knickdeichsel.SoftKey_heben.IX'"/>
		</FB>
		<FB Name="UT_SoftkeyMapping_UP" Type="UT_SoftkeyMapping_UP" x="1066.67" y="2666.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="isobus::GLOBAL"/>
			<Parameter Name="u16ObjId_2" Value="DefaultPool::SoftKey_Dom"/>
			<Parameter Name="DigitalInput_2" Value="'App.Control.functions.Dom.SoftKey'"/>
			<Parameter Name="u16ObjId_3" Value="DefaultPool::SoftKey_Heckschieber"/>
			<Parameter Name="DigitalInput_3" Value="'App.Control.functions.Heckschieber.SoftKey'"/>
			<Parameter Name="u16ObjId_5" Value="DefaultPool::SoftKey_Schneidwerk"/>
			<Parameter Name="DigitalInput_5" Value="'App.Control.functions.Schneidwerk.SoftKey'"/>
			<Parameter Name="u16ObjId_6" Value="DefaultPool::SoftKey_Seitenschieber"/>
			<Parameter Name="DigitalInput_6" Value="'App.Control.functions.Seitenschieber.SoftKey'"/>
			<Parameter Name="u16ObjId_7" Value="DefaultPool::SoftKey_Abscheider"/>
			<Parameter Name="DigitalInput_7" Value="'App.Control.functions.Abscheider.SoftKey'"/>
			<Parameter Name="u16ObjId_8" Value="DefaultPool::SoftKey_Licht"/>
			<Parameter Name="DigitalInput_8" Value="'App.Control.functions.Licht.SoftKey'"/>
		</FB>
		<SubApp Name="F" Type="F" x="-2800" y="300">
			<Parameter Name="QI" Value="'App.Control.functions.Automatik.ein.SoftKey'"/>
		</SubApp>
		<SubApp Name="F_1" Type="F" x="-2800" y="700">
			<Parameter Name="QI" Value="'App.Control.functions.Klappen.SoftKey_heben.IX'"/>
		</SubApp>
		<SubApp Name="F_2" x="-2800" y="1100">
			<SubAppInterfaceList>
				<InputVars>
					<VarDeclaration Name="QI" Type="STRING" InitialValue="'App.Control.functions.Verteiler.SoftKey_senken.IX'">
						<Attribute Name="VarConfig" Value="false"/>
					</VarDeclaration>
				</InputVars>
				<OutputVars>
					<VarDeclaration Name="QO" Type="STRING">
						<Attribute Name="VarConfig" Value="false"/>
					</VarDeclaration>
				</OutputVars>
			</SubAppInterfaceList>
			<SubAppNetwork>
				<DataConnections>
					<Connection Source="QI" Destination="QO"/>
				</DataConnections>
			</SubAppNetwork>
			<Attribute Name="width" Type="LREAL" Value="200"/>
			<Attribute Name="height" Type="LREAL" Value="100"/>
		</SubApp>
		<DataConnections>
			<Connection Source="F.QO" Destination="UT_SoftkeyMapping.DigitalInput_1" dx1="586.67"/>
			<Connection Source="F_1.QO" Destination="UT_SoftkeyMapping.DigitalInput_2"/>
			<Connection Source="F_2.QO" Destination="UT_SoftkeyMapping.DigitalInput_3" dx1="606.67"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
