<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_blink" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-04-04">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="Initialization Request">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="PKP_2200_LI_4_DI" Type="PKP_2200_LI_4_DI" Comment="" x="726.6666666666667" y="526.6666666666667">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="PKP_2200_DEFAULT" Comment=""/>
			<Parameter Name="u16ObjId" Value="65535" Comment=""/>
			<Parameter Name="DigitalInput_Key_1" Value="'Ventilsteuerung.functions.Knickdeichsel_heben.IX'" Comment=""/>
			<Parameter Name="DigitalInput_Key_3" Value="'Ventilsteuerung.functions.Knickdeichsel_senken.IX'" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="PKP_2200_LI_4_DI.INIT" Comment="" dx1="1033.3333333333335">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
