<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_aux" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event">
				<Attribute Name="YPOSITION" Type="INT" Value="373"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="UT_AuxiliaryInputMapping" Type="UT_AuxiliaryInputMapping_Type_02_Bool_NonLatched" x="-1600" y="-1066.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="GLOBAL"/>
			<Parameter Name="u16ObjId_1" Value="AuxInput_Automatik_ein"/>
			<Parameter Name="DigitalInput_1" Value="'Ventilsteuerung.functions.Automatik.ein.AuxInput'"/>
			<Parameter Name="u16ObjId_2" Value="AuxInput_Auseinanderklappen"/>
			<Parameter Name="DigitalInput_2" Value="'Ventilsteuerung.functions.Klappen.AuxInput_heben.IX'"/>
			<Parameter Name="u16ObjId_3" Value="AuxInput_Verteiler_senken"/>
			<Parameter Name="DigitalInput_3" Value="'Ventilsteuerung.functions.Verteiler.AuxInput_senken.IX'"/>
			<Parameter Name="u16ObjId_4" Value="AuxInput_Knickdeichsel_senken"/>
			<Parameter Name="DigitalInput_4" Value="'Ventilsteuerung.functions.Knickdeichsel.AuxInput_senken.IX'"/>
			<Parameter Name="u16ObjId_5" Value="AuxInput_Automatik_aus"/>
			<Parameter Name="DigitalInput_5" Value="'Ventilsteuerung.functions.Automatik.aus.AuxInput'"/>
			<Parameter Name="u16ObjId_6" Value="AuxInput_Zusammenklappen"/>
			<Parameter Name="DigitalInput_6" Value="'Ventilsteuerung.functions.Klappen.AuxInput_senken.IX'"/>
			<Parameter Name="u16ObjId_7" Value="AuxInput_Verteiler_heben"/>
			<Parameter Name="DigitalInput_7" Value="'Ventilsteuerung.functions.Verteiler.AuxInput_heben.IX'"/>
			<Parameter Name="u16ObjId_8" Value="AuxInput_Knickdeichsel_heben"/>
			<Parameter Name="DigitalInput_8" Value="'Ventilsteuerung.functions.Knickdeichsel.AuxInput_heben.IX'"/>
		</FB>
		<FB Name="UT_AuxiliaryInputMapping_1" Type="UT_AuxiliaryInputMapping_Type_02_Bool_NonLatched_UP" x="-1600" y="1600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="GLOBAL"/>
			<Parameter Name="u16ObjId_2" Value="AuxInput_Dom"/>
			<Parameter Name="DigitalInput_2" Value="'Ventilsteuerung.functions.Dom.AuxInput'"/>
			<Parameter Name="u16ObjId_3" Value="AuxInput_Heckschieber"/>
			<Parameter Name="DigitalInput_3" Value="'Ventilsteuerung.functions.Heckschieber.AuxInput'"/>
			<Parameter Name="u16ObjId_5" Value="AuxInput_Schneidwerk"/>
			<Parameter Name="DigitalInput_5" Value="'Ventilsteuerung.functions.Schneidwerk.AuxInput'"/>
			<Parameter Name="u16ObjId_6" Value="AuxInput_Seitenschieber"/>
			<Parameter Name="DigitalInput_6" Value="'Ventilsteuerung.functions.Seitenschieber.AuxInput'"/>
			<Parameter Name="u16ObjId_7" Value="AuxInput_Abscheider"/>
			<Parameter Name="DigitalInput_7" Value="'Ventilsteuerung.functions.Abscheider.AuxInput'"/>
			<Parameter Name="u16ObjId_8" Value="AuxInput_Licht"/>
			<Parameter Name="DigitalInput_8" Value="'Ventilsteuerung.functions.Licht.AuxInput'"/>
		</FB>
		<FB Name="UT_AuxiliaryInputMapping_2" Type="UT_AuxiliaryInputMapping_Type_02_Bool_NonLatched" x="-2100" y="4400">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="GLOBAL"/>
			<Parameter Name="u16ObjId_1" Value="PAGE_1_AUX"/>
			<Parameter Name="DigitalInput_1" Value="'Ventilsteuerung.functions.PAGES.PAGE_1.AUX'"/>
			<Parameter Name="u16ObjId_2" Value="PAGE_2_AUX"/>
			<Parameter Name="DigitalInput_2" Value="'Ventilsteuerung.functions.PAGES.PAGE_2.AUX'"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="UT_AuxiliaryInputMapping.INIT" dx1="80">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="UT_AuxiliaryInputMapping_1.INIT" dx1="80" dx2="80" dy="0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="UT_AuxiliaryInputMapping_2.INIT" dx1="80">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
