<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2024-03-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="mapping_AuxFunction2_IE" Type="mapping_AuxFunction2_IE" x="-1800" y="1400">
		</SubApp>
		<SubApp Name="mapping_AuxFunction2_IX" Type="mapping_AuxFunction2_IX" x="-1800" y="1700">
		</SubApp>
		<SubApp Name="mapping_blink" Type="mapping_blink" x="-1800" y="2000">
		</SubApp>
		<SubApp Name="mapping_Buttons_IE" Type="mapping_Buttons_IE" x="-1800" y="2300">
		</SubApp>
		<SubApp Name="mapping_Buttons_IX" Type="mapping_Buttons_IX" x="-1800" y="2600">
		</SubApp>
		<SubApp Name="mapping_DataPanel_QX" Type="mapping_DO_QX" x="-1800" y="2900">
		</SubApp>
		<SubApp Name="mapping_Softkeys_IE" Type="mapping_Softkeys_IE" x="-1800" y="3200">
		</SubApp>
		<SubApp Name="mapping_Softkeys_IX" Type="mapping_Softkeys_IX" x="-1800" y="3500">
		</SubApp>
	</SubAppNetwork>
</SubAppType>
