<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Softkeys_IX" Comment="Mapping for all Softkey" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="UT_SoftkeyMapping" Type="UT_SoftkeyMapping" x="5353.33" y="3026.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="isobus::GLOBAL"/>
			<Parameter Name="u16ObjId_1" Value="DefaultPool::SoftKey_Automatik_ein"/>
			<Parameter Name="u16ObjId_2" Value="DefaultPool::SoftKey_Auseinanderklappen"/>
			<Parameter Name="u16ObjId_3" Value="DefaultPool::SoftKey_Verteiler_senken"/>
			<Parameter Name="u16ObjId_4" Value="DefaultPool::SoftKey_Knickdeichsel_senken"/>
			<Parameter Name="u16ObjId_5" Value="DefaultPool::SoftKey_Automatik_aus"/>
			<Parameter Name="u16ObjId_6" Value="DefaultPool::SoftKey_Zusammenklappen"/>
			<Parameter Name="u16ObjId_7" Value="DefaultPool::SoftKey_Verteiler_heben"/>
			<Parameter Name="u16ObjId_8" Value="DefaultPool::SoftKey_Knickdeichsel_heben"/>
		</FB>
		<SubApp Name="MF" Type="MF" x="2713.33" y="3873.33">
			<Parameter Name="DI1" Value="'App.Control.functions.Automatik.ein.SoftKey'"/>
			<Parameter Name="DI2" Value="'App.Control.functions.Klappen.SoftKey_heben.IX'"/>
			<Parameter Name="DI3" Value="'App.Control.functions.Verteiler.SoftKey_senken.IX'"/>
			<Parameter Name="DI4" Value="'App.Control.functions.Knickdeichsel.SoftKey_senken.IX'"/>
			<Parameter Name="DI5" Value="'App.Control.functions.Automatik.aus.SoftKey'"/>
			<Parameter Name="DI6" Value="'App.Control.functions.Klappen.SoftKey_senken.IX'"/>
			<Parameter Name="DI7" Value="'App.Control.functions.Verteiler.SoftKey_heben.IX'"/>
			<Parameter Name="DI8" Value="'App.Control.functions.Knickdeichsel.SoftKey_heben.IX'"/>
		</SubApp>
		<DataConnections>
			<Connection Source="MF.DO1" Destination="UT_SoftkeyMapping.DigitalInput_1" dx1="73.33"/>
			<Connection Source="MF.DO2" Destination="UT_SoftkeyMapping.DigitalInput_2" dx1="140"/>
			<Connection Source="MF.DO3" Destination="UT_SoftkeyMapping.DigitalInput_3" dx1="206.67"/>
			<Connection Source="MF.DO4" Destination="UT_SoftkeyMapping.DigitalInput_4" dx1="73.33"/>
			<Connection Source="MF.DO5" Destination="UT_SoftkeyMapping.DigitalInput_5" dx1="73.33"/>
			<Connection Source="MF.DO6" Destination="UT_SoftkeyMapping.DigitalInput_6" dx1="206.67"/>
			<Connection Source="MF.DO7" Destination="UT_SoftkeyMapping.DigitalInput_7" dx1="140"/>
			<Connection Source="MF.DO8" Destination="UT_SoftkeyMapping.DigitalInput_8" dx1="73.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
