<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Buttons_IX" Comment="Mapping for all Button IX">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="UT_ButtonMapping_UP" Type="UT_ButtonMapping_UP" x="900" y="900">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u16ObjId_1" Value="DefaultPool::PAGE_1_BTN"/>
			<Parameter Name="DigitalInput_1" Value="'App.Control.PAGES.PAGE_1.BTN'"/>
			<Parameter Name="u16ObjId_2" Value="DefaultPool::PAGE_2_BTN"/>
			<Parameter Name="DigitalInput_2" Value="'App.Control.PAGES.PAGE_2.BTN'"/>
		</FB>
	</SubAppNetwork>
</SubAppType>
