<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Softkeys" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="UT_SoftkeyMapping" Type="UT_SoftkeyMapping" x="1066.67" y="0">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="GLOBAL"/>
			<Parameter Name="u16ObjId_1" Value="SoftKey_Automatik_ein"/>
			<Parameter Name="DigitalInput_1" Value="'Ventilsteuerung.functions.Automatik.ein.SoftKey'"/>
			<Parameter Name="u16ObjId_2" Value="SoftKey_Auseinanderklappen"/>
			<Parameter Name="DigitalInput_2" Value="'Ventilsteuerung.functions.Klappen.SoftKey_heben.IX'"/>
			<Parameter Name="u16ObjId_3" Value="SoftKey_Verteiler_senken"/>
			<Parameter Name="DigitalInput_3" Value="'Ventilsteuerung.functions.Verteiler.SoftKey_senken.IX'"/>
			<Parameter Name="u16ObjId_4" Value="SoftKey_Knickdeichsel_senken"/>
			<Parameter Name="DigitalInput_4" Value="'Ventilsteuerung.functions.Knickdeichsel.SoftKey_senken.IX'"/>
			<Parameter Name="u16ObjId_5" Value="SoftKey_Automatik_aus"/>
			<Parameter Name="DigitalInput_5" Value="'Ventilsteuerung.functions.Automatik.aus.SoftKey'"/>
			<Parameter Name="u16ObjId_6" Value="SoftKey_Zusammenklappen"/>
			<Parameter Name="DigitalInput_6" Value="'Ventilsteuerung.functions.Klappen.SoftKey_senken.IX'"/>
			<Parameter Name="u16ObjId_7" Value="SoftKey_Verteiler_heben"/>
			<Parameter Name="DigitalInput_7" Value="'Ventilsteuerung.functions.Verteiler.SoftKey_heben.IX'"/>
			<Parameter Name="u16ObjId_8" Value="SoftKey_Knickdeichsel_heben"/>
			<Parameter Name="DigitalInput_8" Value="'Ventilsteuerung.functions.Knickdeichsel.SoftKey_heben.IX'"/>
		</FB>
		<FB Name="UT_SoftkeyMapping_UP" Type="UT_SoftkeyMapping_UP" x="1066.67" y="2666.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="GLOBAL"/>
			<Parameter Name="u16ObjId_2" Value="SoftKey_Dom"/>
			<Parameter Name="DigitalInput_2" Value="'Ventilsteuerung.functions.Dom.SoftKey'"/>
			<Parameter Name="u16ObjId_3" Value="SoftKey_Heckschieber"/>
			<Parameter Name="DigitalInput_3" Value="'Ventilsteuerung.functions.Heckschieber.SoftKey'"/>
			<Parameter Name="u16ObjId_5" Value="SoftKey_Schneidwerk"/>
			<Parameter Name="DigitalInput_5" Value="'Ventilsteuerung.functions.Schneidwerk.SoftKey'"/>
			<Parameter Name="u16ObjId_6" Value="SoftKey_Seitenschieber"/>
			<Parameter Name="DigitalInput_6" Value="'Ventilsteuerung.functions.Seitenschieber.SoftKey'"/>
			<Parameter Name="u16ObjId_7" Value="SoftKey_Abscheider"/>
			<Parameter Name="DigitalInput_7" Value="'Ventilsteuerung.functions.Abscheider.SoftKey'"/>
			<Parameter Name="u16ObjId_8" Value="SoftKey_Licht"/>
			<Parameter Name="DigitalInput_8" Value="'Ventilsteuerung.functions.Licht.SoftKey'"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="UT_SoftkeyMapping.INIT" dx1="80">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="UT_SoftkeyMapping_UP.INIT" dx1="80">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
