<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_DataPanel" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DataPanel_xDB_16_DO_SAE_J1939" Type="DataPanel_xDB_16_DO_SAE_J1939" Comment="" x="1246.67" y="13.33">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="MI_00" Comment=""/>
			<Parameter Name="u16ObjId" Value="isobus::ID_NULL" Comment=""/>
			<Parameter Name="DigitalOutput_1A" Value="'App.Control.functions.Schneidwerk.rechtslauf'" Comment=""/>
			<Parameter Name="DigitalOutput_1B" Value="'App.Control.functions.Schneidwerk.linkslauf'" Comment=""/>
			<Parameter Name="DigitalOutput_2A" Value="'App.Control.functions.Vorsteuerventil_2A.QX'" Comment=""/>
			<Parameter Name="DigitalOutput_2B" Value="'App.Control.functions.Vorsteuerventil_2B.QX'" Comment=""/>
			<Parameter Name="DigitalOutput_3A" Value="'App.Control.functions.Klappen.Sitzventile.QXA'" Comment=""/>
			<Parameter Name="DigitalOutput_3B" Value="'App.Control.functions.Klappen.Sitzventile.QXB'" Comment=""/>
			<Parameter Name="DigitalOutput_4A" Value="'App.Control.functions.Verteiler.Sitzventile.QXA'" Comment=""/>
			<Parameter Name="DigitalOutput_4B" Value="'App.Control.functions.Verteiler.Sitzventile.QXB'" Comment=""/>
			<Parameter Name="DigitalOutput_5A" Value="'App.Control.functions.Knickdeichsel.Sitzventile.QXA'" Comment=""/>
			<Parameter Name="DigitalOutput_5B" Value="'App.Control.functions.Knickdeichsel.Sitzventile.QXB'" Comment=""/>
			<Parameter Name="DigitalOutput_6A" Value="'App.Control.functions.Dom.QX'" Comment=""/>
			<Parameter Name="DigitalOutput_6B" Value="'App.Control.functions.Heckschieber.QXB'" Comment=""/>
			<Parameter Name="DigitalOutput_7A" Value="'App.Control.functions.Seitenschieber.QX'" Comment=""/>
			<Parameter Name="DigitalOutput_7B" Value="'App.Control.functions.Abscheider.QX'" Comment=""/>
			<Parameter Name="DigitalOutput_8A" Value="'App.Control.functions.Licht.QX'" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="DataPanel_xDB_16_DO_SAE_J1939.INIT" Comment="" dx1="640">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
