<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_blink" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-04-04">
	</VersionInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="PKP_2200_LI_4_DI" Type="PKP_2200_LI_4_DI" x="726.67" y="526.67">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="PKP_2200::DEFAULT"/>
			<Parameter Name="u16ObjId" Value="isobus::ID_NULL"/>
			<Parameter Name="DigitalInput_Key_1" Value="'App.Control.functions.Knickdeichsel_heben.IX'"/>
			<Parameter Name="DigitalInput_Key_2" Value="'App.Control.functions.Seitenschieber_Auf.IX'"/>
			<Parameter Name="DigitalInput_Key_3" Value="'App.Control.functions.Knickdeichsel_senken.IX'"/>
			<Parameter Name="DigitalInput_Key_4" Value="'App.Control.functions.Seitenschieber_Zu.IX'"/>
		</FB>
	</SubAppNetwork>
</SubAppType>
