<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_DataPanel_QX" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="DataPanel_xDB_16_DO_SAE_J1939" Type="DataPanel_xDB_16_DO_SAE_J1939" x="1246.67" y="13.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="MI::MI_00"/>
			<Parameter Name="u16ObjId" Value="isobus::ID_NULL"/>
			<Parameter Name="DigitalOutput_1A" Value="'App.Control.functions.Schneidwerk.rechtslauf'"/>
			<Parameter Name="DigitalOutput_1B" Value="'App.Control.functions.Schneidwerk.linkslauf'"/>
			<Parameter Name="DigitalOutput_2A" Value="'App.Control.functions.Vorsteuerventil_2A.QX'"/>
			<Parameter Name="DigitalOutput_2B" Value="'App.Control.functions.Vorsteuerventil_2B.QX'"/>
			<Parameter Name="DigitalOutput_3A" Value="'App.Control.functions.Klappen.Sitzventile.QXA'"/>
			<Parameter Name="DigitalOutput_3B" Value="'App.Control.functions.Klappen.Sitzventile.QXB'"/>
			<Parameter Name="DigitalOutput_4A" Value="'App.Control.functions.Verteiler.Sitzventile.QXA'"/>
			<Parameter Name="DigitalOutput_4B" Value="'App.Control.functions.Verteiler.Sitzventile.QXB'"/>
			<Parameter Name="DigitalOutput_5A" Value="'App.Control.functions.Knickdeichsel.Sitzventile.QXA'"/>
			<Parameter Name="DigitalOutput_5B" Value="'App.Control.functions.Knickdeichsel.Sitzventile.QXB'"/>
			<Parameter Name="DigitalOutput_6A" Value="'App.Control.functions.Dom.QX'"/>
			<Parameter Name="DigitalOutput_6B" Value="'App.Control.functions.Heckschieber.QXB'"/>
			<Parameter Name="DigitalOutput_7A" Value="'App.Control.functions.Seitenschieber.QX'"/>
			<Parameter Name="DigitalOutput_7B" Value="'App.Control.functions.Abscheider.QX'"/>
			<Parameter Name="DigitalOutput_8A" Value="'App.Control.functions.Licht.QX'"/>
		</FB>
	</SubAppNetwork>
</SubAppType>
