<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Softkeys_IX" Comment="Mapping for all Softkey" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="UT_SoftkeyMapping" Type="UT_SoftkeyMapping" x="5000" y="2600">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="isobus::GLOBAL"/>
			<Parameter Name="u16ObjId_1" Value="DefaultPool::SoftKey_Automatik_ein"/>
			<Parameter Name="u16ObjId_2" Value="DefaultPool::SoftKey_Auseinanderklappen"/>
			<Parameter Name="u16ObjId_3" Value="DefaultPool::SoftKey_Verteiler_senken"/>
			<Parameter Name="u16ObjId_4" Value="DefaultPool::SoftKey_Knickdeichsel_senken"/>
			<Parameter Name="u16ObjId_5" Value="DefaultPool::SoftKey_Automatik_aus"/>
			<Parameter Name="u16ObjId_6" Value="DefaultPool::SoftKey_Zusammenklappen"/>
			<Parameter Name="u16ObjId_7" Value="DefaultPool::SoftKey_Verteiler_heben"/>
			<Parameter Name="u16ObjId_8" Value="DefaultPool::SoftKey_Knickdeichsel_heben"/>
		</FB>
		<SubApp Name="F" Type="F" x="2100" y="2900">
			<Parameter Name="QI" Value="'App.Control.functions.Automatik.ein.SoftKey'"/>
		</SubApp>
		<SubApp Name="F_1" Type="F" x="2100" y="3200">
			<Parameter Name="QI" Value="'App.Control.functions.Klappen.SoftKey_heben.IX'"/>
		</SubApp>
		<SubApp Name="F_2" Type="F" x="2100" y="3500">
			<Parameter Name="QI" Value="'App.Control.functions.Verteiler.SoftKey_senken.IX'"/>
		</SubApp>
		<SubApp Name="F_3" Type="F" x="2100" y="3800">
			<Parameter Name="QI" Value="'App.Control.functions.Knickdeichsel.SoftKey_senken.IX'"/>
		</SubApp>
		<SubApp Name="F_4" Type="F" x="2100" y="4100">
			<Parameter Name="QI" Value="'App.Control.functions.Automatik.aus.SoftKey'"/>
		</SubApp>
		<SubApp Name="F_5" Type="F" x="2100" y="4400">
			<Parameter Name="QI" Value="'App.Control.functions.Klappen.SoftKey_senken.IX'"/>
		</SubApp>
		<SubApp Name="F_6" Type="F" x="2100" y="4700">
			<Parameter Name="QI" Value="'App.Control.functions.Verteiler.SoftKey_heben.IX'"/>
		</SubApp>
		<SubApp Name="F_7" Type="F" x="2100" y="5000">
			<Parameter Name="QI" Value="'App.Control.functions.Knickdeichsel.SoftKey_heben.IX'"/>
		</SubApp>
		<DataConnections>
			<Connection Source="F_2.QO" Destination="UT_SoftkeyMapping.DigitalInput_3"/>
			<Connection Source="F_3.QO" Destination="UT_SoftkeyMapping.DigitalInput_4" dx1="226.67"/>
			<Connection Source="F_4.QO" Destination="UT_SoftkeyMapping.DigitalInput_5" dx1="313.33"/>
			<Connection Source="F_5.QO" Destination="UT_SoftkeyMapping.DigitalInput_6" dx1="433.33"/>
			<Connection Source="F_6.QO" Destination="UT_SoftkeyMapping.DigitalInput_7" dx1="586.67"/>
			<Connection Source="F_7.QO" Destination="UT_SoftkeyMapping.DigitalInput_8" dx1="766.67"/>
			<Connection Source="F_1.QO" Destination="UT_SoftkeyMapping.DigitalInput_2" dx1="80"/>
			<Connection Source="F.QO" Destination="UT_SoftkeyMapping.DigitalInput_1" dx1="620"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
