<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="MF" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2025-02-12">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="DI1" Type="STRING"/>
			<VarDeclaration Name="DI2" Type="STRING"/>
			<VarDeclaration Name="DI3" Type="STRING"/>
			<VarDeclaration Name="DI4" Type="STRING"/>
			<VarDeclaration Name="DI5" Type="STRING"/>
			<VarDeclaration Name="DI6" Type="STRING"/>
			<VarDeclaration Name="DI7" Type="STRING"/>
			<VarDeclaration Name="DI8" Type="STRING"/>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="DO1" Type="STRING"/>
			<VarDeclaration Name="DO2" Type="STRING"/>
			<VarDeclaration Name="DO3" Type="STRING"/>
			<VarDeclaration Name="DO4" Type="STRING"/>
			<VarDeclaration Name="DO5" Type="STRING"/>
			<VarDeclaration Name="DO6" Type="STRING"/>
			<VarDeclaration Name="DO7" Type="STRING"/>
			<VarDeclaration Name="DO8" Type="STRING"/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
	</SubAppNetwork>
</SubAppType>
