<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Automatik" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="CNF_Schieber" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="EO_Verteiler_heben" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="EO_Verteiler_senken" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="EO_Automatik_ein" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="EO_Automatik_ein_UP" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="EO_Automatik_aus_DOWN" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventOutputs>
		<OutputVars>
			<VarDeclaration Name="Q_Verteiler_heben" Type="BOOL" Comment=""/>
			<VarDeclaration Name="Q_Verteiler_senken" Type="BOOL" Comment=""/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_SR_Verteiler_heben" Type="E_SR" Comment="" x="4800.0" y="3993.3333333333335">
		</FB>
		<FB Name="E_REND_Automatik_aus" Type="E_REND" Comment="" x="3720.0" y="2920.0">
		</FB>
		<FB Name="E_SR_Verteiler_senken" Type="E_SR" Comment="" x="2306.666666666667" y="1053.3333333333335">
		</FB>
		<FB Name="E_REND_Automatik_ein" Type="E_REND" Comment="" x="4246.666666666667" y="1593.3333333333335">
		</FB>
		<FB Name="E_FWD_DLY_Automatik_ein_UP" Type="E_DELAY" Comment="" x="1853.3333333333335" y="1593.3333333333335">
			<Parameter Name="DT" Value="T#10ms"/>
		</FB>
		<FB Name="E_FWD_DLY_Automatik_aus_DOWN" Type="E_DELAY" Comment="" x="2393.3333333333335" y="2446.666666666667">
			<Parameter Name="DT" Value="T#10ms"/>
		</FB>
		<SubApp Name="Automatik_ein" Type="Automatik_ein" Comment="" x="-500.0" y="500.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="Automatik_aus" Type="Automatik_aus" Comment="" x="-600.0" y="2600.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<EventConnections>
			<Connection Source="E_REND_Automatik_aus.EO" Destination="E_SR_Verteiler_heben.S" Comment="" dx1="46.66666666666667"/>
			<Connection Source="E_SR_Verteiler_heben.EO" Destination="EO_Verteiler_heben" Comment="" dx1="140.0"/>
			<Connection Source="E_SR_Verteiler_senken.EO" Destination="EO_Verteiler_senken" Comment="" dx1="2760.0"/>
			<Connection Source="CNF_Schieber" Destination="E_REND_Automatik_ein.EI1" Comment="" dx1="4193.333333333334"/>
			<Connection Source="E_REND_Automatik_ein.EO" Destination="EO_Automatik_ein" Comment="" dx1="1013.3333333333334"/>
			<Connection Source="CNF_Schieber" Destination="E_REND_Automatik_aus.EI1" Comment="" dx1="3700.0" dx2="1366.6666666666667" dy="2213.3333333333335"/>
			<Connection Source="E_FWD_DLY_Automatik_ein_UP.EO" Destination="E_REND_Automatik_ein.EI2" Comment="" dx1="713.3333333333334"/>
			<Connection Source="E_FWD_DLY_Automatik_aus_DOWN.EO" Destination="E_REND_Automatik_aus.EI2" Comment="" dx1="1093.3333333333335" dx2="46.66666666666667" dy="1086.6666666666667"/>
			<Connection Source="INIT" Destination="Automatik_ein.INIT" Comment="" dx1="413.33333333333337" dx2="413.33333333333337" dy="0.0"/>
			<Connection Source="Automatik_ein.Automatik_ein_DOWN" Destination="E_SR_Verteiler_senken.S" Comment="" dx1="1253.3333333333335" dx2="1253.3333333333335" dy="0.0"/>
			<Connection Source="Automatik_ein.Automatik_ein_UP" Destination="E_SR_Verteiler_senken.R" Comment="" dx1="1253.3333333333335" dx2="1253.3333333333335" dy="0.0"/>
			<Connection Source="Automatik_ein.Automatik_ein_UP" Destination="E_REND_Automatik_ein.R" Comment="" dx1="2193.3333333333335" dx2="2193.3333333333335" dy="0.0"/>
			<Connection Source="Automatik_ein.Automatik_ein_UP" Destination="EO_Automatik_ein_UP" Comment="" dx1="3306.666666666667" dx2="3306.666666666667" dy="0.0"/>
			<Connection Source="Automatik_ein.Automatik_ein_UP" Destination="E_FWD_DLY_Automatik_ein_UP.START" Comment="" dx1="1053.3333333333335" dx2="1053.3333333333335" dy="0.0"/>
			<Connection Source="INIT" Destination="Automatik_aus.INIT" Comment="" dx1="360.0" dx2="360.0" dy="0.0"/>
			<Connection Source="Automatik_aus.Automatik_aus_DOWN" Destination="E_REND_Automatik_aus.R" Comment="" dx1="1980.0" dx2="1980.0" dy="0.0"/>
			<Connection Source="Automatik_aus.Automatik_aus_DOWN" Destination="EO_Automatik_aus_DOWN" Comment="" dx1="3353.3333333333335" dx2="3353.3333333333335" dy="0.0"/>
			<Connection Source="Automatik_aus.Automatik_aus_DOWN" Destination="E_FWD_DLY_Automatik_aus_DOWN.START" Comment="" dx1="1393.3333333333335" dx2="1393.3333333333335" dy="0.0"/>
			<Connection Source="Automatik_aus.Automatik_aus_UP" Destination="E_SR_Verteiler_heben.R" Comment="" dx1="2540.0" dx2="2540.0" dy="0.0"/>
			<Connection Source="Automatik_aus.Automatik_aus_UP" Destination="E_REND_Automatik_aus.R" Comment="" dx1="1980.0" dx2="1980.0" dy="0.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_SR_Verteiler_heben.Q" Destination="Q_Verteiler_heben" Comment="" dx1="46.66666666666667" dx2="246.66666666666669" dy="-860.0"/>
			<Connection Source="E_SR_Verteiler_senken.Q" Destination="Q_Verteiler_senken" Comment="" dx1="46.66666666666667" dx2="753.3333333333334" dy="-853.3333333333334"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
