<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Automatik_ein" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-11">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="Automatik_ein_DOWN" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="Automatik_ein_UP" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventOutputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_Automatik_ein_DOWN" Type="IE" Comment="" x="0.0" y="0.0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="SoftKey_Automatik_ein_UP" Type="IE" Comment="" x="0.0" y="1100.0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="SoftKey_Automatik_ein_DOWN.INIT" Comment="" dx1="80.0" dx2="80.0" dy="-13.333333333333334"/>
			<Connection Source="SoftKey_Automatik_ein_DOWN.IND" Destination="Automatik_ein_DOWN" Comment="" dx1="2886.666666666667"/>
			<Connection Source="INIT" Destination="SoftKey_Automatik_ein_UP.INIT" Comment="" dx1="80.0" dx2="80.0" dy="533.3333333333334"/>
			<Connection Source="SoftKey_Automatik_ein_UP.IND" Destination="Automatik_ein_UP" Comment="" dx1="2913.3333333333335"/>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
