<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GreenWhiteBackground_Zusammenklappen" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-11">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="CNF" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="OUT" Type="BOOL" Comment=""/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="GreenWhiteBackground_Zusammenklappen" Type="GreenWhiteBackground" Comment="" x="0.0" y="0.0">
			<Parameter Name="u16ObjId" Value="5004"/>
			<Parameter Name="u16ObjIdA" Value="31004"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="GreenWhiteBackground_Zusammenklappen.INIT" Comment=""/>
			<Connection Source="CNF" Destination="GreenWhiteBackground_Zusammenklappen.REQ" Comment=""/>
		</EventConnections>
		<DataConnections>
			<Connection Source="OUT" Destination="GreenWhiteBackground_Zusammenklappen.DI1" Comment=""/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
