<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Klappen_Sitzventile" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-11">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INITO" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="20"/>
			</SubAppEvent>
			<SubAppEvent Name="CNF_Auseinanderklappen" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="0"/>
			</SubAppEvent>
			<SubAppEvent Name="CNF_Zusammenklappen" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="0"/>
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="IN_Auseinanderklappen" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="265"/>
			</VarDeclaration>
			<VarDeclaration Name="IN_Zusammenklappen" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="0"/>
			</VarDeclaration>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="OR_4A_4B" Type="OR_2" Comment="" x="-713.3333333333334" y="526.6666666666667">
			<Attribute Name="PinComment" Type="STRING" Value="IN1:Auseinanderklappen"/>
			<Attribute Name="PinComment" Type="STRING" Value="IN2:Zusammenklappen"/>
		</FB>
		<FB Name="Klappen_3B" Type="QX" Comment="" x="293.33333333333337" y="526.6666666666667">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Klappen_3A" Type="QX" Comment="" x="293.33333333333337" y="1366.6666666666667">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="OR_4A_4B.CNF" Destination="Klappen_3B.REQ" Comment="" dx1="253.33333333333334"/>
			<Connection Source="OR_4A_4B.CNF" Destination="Klappen_3A.REQ" Comment="" dx1="106.66666666666667"/>
			<Connection Source="CNF_Auseinanderklappen" Destination="OR_4A_4B.REQ" Comment="" dx1="333.33333333333337"/>
			<Connection Source="CNF_Zusammenklappen" Destination="OR_4A_4B.REQ" Comment="" dx1="226.66666666666669"/>
			<Connection Source="INITO" Destination="Klappen_3B.INIT" Comment="" dx1="1353.3333333333335"/>
			<Connection Source="INITO" Destination="Klappen_3A.INIT" Comment="" dx1="1246.6666666666667"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="OR_4A_4B.OUT" Destination="Klappen_3B.OUT" Comment="" dx1="193.33333333333334"/>
			<Connection Source="OR_4A_4B.OUT" Destination="Klappen_3A.OUT" Comment="" dx1="60.0"/>
			<Connection Source="IN_Auseinanderklappen" Destination="OR_4A_4B.IN1" Comment="" dx1="93.33333333333334"/>
			<Connection Source="IN_Zusammenklappen" Destination="OR_4A_4B.IN2" Comment="" dx1="200.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
