<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Klappen_Sitzventile" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-11">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INITO" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="CNF_Auseinanderklappen" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="CNF_Zusammenklappen" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="IN_Auseinanderklappen" Type="BOOL" Comment=""/>
			<VarDeclaration Name="IN_Zusammenklappen" Type="BOOL" Comment=""/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="OR_4A_4B" Type="OR_2" Comment="" x="673.3333333333334" y="566.6666666666667">
			<Attribute Name="PinComment" Type="STRING" Value="IN1:Auseinanderklappen"/>
			<Attribute Name="PinComment" Type="STRING" Value="IN2:Zusammenklappen"/>
		</FB>
		<FB Name="Klappen_3B" Type="QX" Comment="" x="2006.6666666666667" y="173.33333333333334">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Klappen_3A" Type="QX" Comment="" x="2140.0" y="1240.0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="OR_4A_4B.CNF" Destination="Klappen_3B.REQ" Comment="" dx1="293.33333333333337"/>
			<Connection Source="OR_4A_4B.CNF" Destination="Klappen_3A.REQ" Comment="" dx1="413.33333333333337"/>
			<Connection Source="CNF_Auseinanderklappen" Destination="OR_4A_4B.REQ" Comment="" dx1="513.3333333333334"/>
			<Connection Source="CNF_Zusammenklappen" Destination="OR_4A_4B.REQ" Comment="" dx1="2860.0" dx2="53.333333333333336" dy="-80.0"/>
			<Connection Source="INITO" Destination="Klappen_3B.INIT" Comment="" dx1="2366.666666666667"/>
			<Connection Source="INITO" Destination="Klappen_3A.INIT" Comment="" dx1="80.0" dx2="53.333333333333336" dy="1140.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="OR_4A_4B.OUT" Destination="Klappen_3B.OUT" Comment="" dx1="520.0"/>
			<Connection Source="OR_4A_4B.OUT" Destination="Klappen_3A.OUT" Comment="" dx1="306.6666666666667"/>
			<Connection Source="IN_Auseinanderklappen" Destination="OR_4A_4B.IN1" Comment="" dx1="2966.666666666667" dx2="333.33333333333337" dy="-180.0"/>
			<Connection Source="IN_Zusammenklappen" Destination="OR_4A_4B.IN2" Comment="" dx1="220.0" dx2="333.33333333333337" dy="633.3333333333334"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
