<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Klappen" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="EI_Auseinanderklappen" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="EI_Zusammenklappen" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF_2b" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="CNF_2a" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="IN_Auseinanderklappen" Type="BOOL" Comment=""/>
			<VarDeclaration Name="IN_Zusammenklappen" Type="BOOL" Comment=""/>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="OUT_2b" Type="BOOL" Comment=""/>
			<VarDeclaration Name="OUT_2a" Type="BOOL" Comment=""/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="GreenWhiteBackground_Auseinanderklappen" Type="GreenWhiteBackground_Auseinanderklappen" Comment="" x="3800.0" y="3300.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="GreenWhiteBackground_Zusammenklappen" Type="GreenWhiteBackground_Zusammenklappen" Comment="" x="3800.0" y="4000.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="Klappen_Sitzventile" Type="Klappen_Sitzventile" Comment="" x="5926.666666666667" y="2520.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<FB Name="OR_2_Auseinanderklappen" Type="OR_3" Comment="" x="2300.0" y="700.0">
		</FB>
		<FB Name="OR_2_Zusammenklappen" Type="OR_3" Comment="" x="2200.0" y="2100.0">
		</FB>
		<SubApp Name="SoftKey_Auseinanderklappen" Type="SoftKey_Auseinanderklappen" Comment="" x="-200.0" y="500.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="SoftKey_Zusammenklappen" Type="SoftKey_Zusammenklappen" Comment="" x="-200.0" y="1500.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="AuxInput_Auseinanderklappen" Type="SoftKey_Auseinanderklappen" Comment="" x="-200.0" y="1000.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="AuxInput_Zusammenklappen" Type="AuxInput_Zusammenklappen" Comment="" x="-200.0" y="2000.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<EventConnections>
			<Connection Source="INIT" Destination="GreenWhiteBackground_Auseinanderklappen.INIT" Comment="" dx1="5060.0"/>
			<Connection Source="INIT" Destination="GreenWhiteBackground_Zusammenklappen.INIT" Comment="" dx1="5060.0"/>
			<Connection Source="INIT" Destination="Klappen_Sitzventile.INITO" Comment="" dx1="7073.333333333334" dx2="5886.666666666667" dy="0.0"/>
			<Connection Source="EI_Auseinanderklappen" Destination="OR_2_Auseinanderklappen.REQ" Comment="" dx1="3566.666666666667"/>
			<Connection Source="OR_2_Auseinanderklappen.CNF" Destination="CNF_2a" Comment="" dx1="5586.666666666667"/>
			<Connection Source="OR_2_Auseinanderklappen.CNF" Destination="GreenWhiteBackground_Auseinanderklappen.CNF" Comment="" dx1="546.6666666666667"/>
			<Connection Source="OR_2_Auseinanderklappen.CNF" Destination="Klappen_Sitzventile.CNF_Auseinanderklappen" Comment="" dx1="2506.666666666667"/>
			<Connection Source="EI_Zusammenklappen" Destination="OR_2_Zusammenklappen.REQ" Comment="" dx1="3406.666666666667"/>
			<Connection Source="OR_2_Zusammenklappen.CNF" Destination="CNF_2b" Comment="" dx1="5333.333333333334"/>
			<Connection Source="OR_2_Zusammenklappen.CNF" Destination="GreenWhiteBackground_Zusammenklappen.CNF" Comment="" dx1="453.33333333333337"/>
			<Connection Source="OR_2_Zusammenklappen.CNF" Destination="Klappen_Sitzventile.CNF_Zusammenklappen" Comment="" dx1="1500.0"/>
			<Connection Source="INIT" Destination="SoftKey_Auseinanderklappen.INIT" Comment="" dx1="713.3333333333334"/>
			<Connection Source="SoftKey_Auseinanderklappen.IND" Destination="OR_2_Auseinanderklappen.REQ" Comment="" dx1="413.33333333333337"/>
			<Connection Source="INIT" Destination="SoftKey_Zusammenklappen.INIT" Comment="" dx1="713.3333333333334"/>
			<Connection Source="SoftKey_Zusammenklappen.IND" Destination="OR_2_Zusammenklappen.REQ" Comment="" dx1="760.0"/>
			<Connection Source="INIT" Destination="AuxInput_Auseinanderklappen.INIT" Comment="" dx1="713.3333333333334"/>
			<Connection Source="AuxInput_Auseinanderklappen.IND" Destination="OR_2_Auseinanderklappen.REQ" Comment="" dx1="413.33333333333337"/>
			<Connection Source="INIT" Destination="AuxInput_Zusammenklappen.INIT" Comment="" dx1="713.3333333333334" dx2="713.3333333333334" dy="0.0"/>
			<Connection Source="AuxInput_Zusammenklappen.IND" Destination="OR_2_Zusammenklappen.REQ" Comment="" dx1="600.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="IN_Auseinanderklappen" Destination="OR_2_Auseinanderklappen.IN2" Comment="" dx1="3246.666666666667"/>
			<Connection Source="OR_2_Auseinanderklappen.OUT" Destination="OUT_2a" Comment="" dx1="6093.333333333334"/>
			<Connection Source="OR_2_Auseinanderklappen.OUT" Destination="GreenWhiteBackground_Auseinanderklappen.OUT" Comment="" dx1="420.0"/>
			<Connection Source="OR_2_Auseinanderklappen.OUT" Destination="Klappen_Sitzventile.IN_Auseinanderklappen" Comment="" dx1="2300.0"/>
			<Connection Source="IN_Zusammenklappen" Destination="OR_2_Zusammenklappen.IN2" Comment="" dx1="173.33333333333334"/>
			<Connection Source="OR_2_Zusammenklappen.OUT" Destination="OUT_2b" Comment="" dx1="6020.0"/>
			<Connection Source="OR_2_Zusammenklappen.OUT" Destination="GreenWhiteBackground_Zusammenklappen.OUT" Comment="" dx1="360.0"/>
			<Connection Source="OR_2_Zusammenklappen.OUT" Destination="Klappen_Sitzventile.IN_Zusammenklappen" Comment="" dx1="1340.0"/>
			<Connection Source="SoftKey_Auseinanderklappen.IN" Destination="OR_2_Auseinanderklappen.IN1" Comment="" dx1="213.33333333333334"/>
			<Connection Source="SoftKey_Zusammenklappen.IN" Destination="OR_2_Zusammenklappen.IN1" Comment="" dx1="426.6666666666667"/>
			<Connection Source="AuxInput_Auseinanderklappen.IN" Destination="OR_2_Auseinanderklappen.IN3" Comment="" dx1="566.6666666666667"/>
			<Connection Source="AuxInput_Zusammenklappen.IN" Destination="OR_2_Zusammenklappen.IN3" Comment="" dx1="246.66666666666669"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
