<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GreenWhiteBackground" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2022-11-10">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="Initialization Request">
			</SubAppEvent>
			<SubAppEvent Name="REQ" Type="Event" Comment="Normal Execution Request">
				<Attribute Name="YPOSITION" Type="INT" Value="175"/>
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="INITO_1" Type="Event" Comment="Initialization Confirm">
				<Attribute Name="YPOSITION" Type="INT" Value="235"/>
			</SubAppEvent>
			<SubAppEvent Name="CNF_1" Type="Event" Comment="Execution Confirmation">
			</SubAppEvent>
			<SubAppEvent Name="INITO_2" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="CNF_2" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="INITO_3" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="CNF_3" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="DI1" Type="BOOL" Comment="Selector">
				<Attribute Name="YPOSITION" Type="INT" Value="18"/>
			</VarDeclaration>
			<VarDeclaration Name="u16ObjId" Type="UINT" Comment="Object ID Softkey">
				<Attribute Name="YPOSITION" Type="INT" Value="45"/>
			</VarDeclaration>
			<VarDeclaration Name="u16ObjIdA" Type="UINT" Comment="Object ID AUX">
				<Attribute Name="YPOSITION" Type="INT" Value="105"/>
			</VarDeclaration>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="STATUS_1" Type="STRING" Comment="Service Status"/>
			<VarDeclaration Name="u8OldColour_1" Type="USINT" Comment="Old value of ID"/>
			<VarDeclaration Name="result_1" Type="INT" Comment="retval see description"/>
			<VarDeclaration Name="STATUS_2" Type="STRING" Comment="Service Status">
				<Attribute Name="YPOSITION" Type="INT" Value="33"/>
			</VarDeclaration>
			<VarDeclaration Name="u8OldColour_2" Type="USINT" Comment="Old value of ID"/>
			<VarDeclaration Name="result_2" Type="INT" Comment="retval see description"/>
			<VarDeclaration Name="STATUS_3" Type="STRING" Comment="Service Status">
				<Attribute Name="YPOSITION" Type="INT" Value="75"/>
			</VarDeclaration>
			<VarDeclaration Name="u8OldColour_3" Type="USINT" Comment="Old value of ID"/>
			<VarDeclaration Name="result_3" Type="INT" Comment="retval see description"/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Q_BackgroundColour_1" Type="Q_BackgroundColour" Comment="" x="1600.0" y="1500.0">
		</FB>
		<FB Name="Q_BackgroundColour_2" Type="Q_BackgroundColour" Comment="" x="1600.0" y="2300.0">
		</FB>
		<FB Name="Q_BackgroundColour_3" Type="Q_BackgroundColourAux" Comment="" x="1600.0" y="3100.0">
		</FB>
		<FB Name="F_SEL_I" Type="F_SEL" Comment="" x="-466.6666666666667" y="1200.0">
			<Parameter Name="IN0" Value="COLOR_WHITE"/>
			<Parameter Name="IN1" Value="COLOR_GREEN"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="Q_BackgroundColour_1.INIT" Comment="" dx1="2800.0"/>
			<Connection Source="INIT" Destination="Q_BackgroundColour_2.INIT" Comment="" dx1="2800.0"/>
			<Connection Source="INIT" Destination="Q_BackgroundColour_3.INIT" Comment="" dx1="2800.0"/>
			<Connection Source="Q_BackgroundColour_3.CNF" Destination="CNF_3" Comment="" dx1="993.3333333333334"/>
			<Connection Source="Q_BackgroundColour_2.CNF" Destination="CNF_2" Comment="" dx1="913.3333333333334"/>
			<Connection Source="Q_BackgroundColour_1.CNF" Destination="CNF_1" Comment="" dx1="380.0"/>
			<Connection Source="Q_BackgroundColour_3.INITO" Destination="INITO_3" Comment="" dx1="866.6666666666667"/>
			<Connection Source="Q_BackgroundColour_2.INITO" Destination="INITO_2" Comment="" dx1="206.66666666666669"/>
			<Connection Source="Q_BackgroundColour_1.INITO" Destination="INITO_1" Comment="" dx1="60.0"/>
			<Connection Source="REQ" Destination="F_SEL_I.REQ" Comment="" dx1="80.0" dx2="80.0" dy="6.666666666666667"/>
			<Connection Source="F_SEL_I.CNF" Destination="Q_BackgroundColour_1.REQ" Comment="" dx1="773.3333333333334" dx2="773.3333333333334" dy="0.0"/>
			<Connection Source="F_SEL_I.CNF" Destination="Q_BackgroundColour_2.REQ" Comment="" dx1="773.3333333333334" dx2="773.3333333333334" dy="0.0"/>
			<Connection Source="F_SEL_I.CNF" Destination="Q_BackgroundColour_3.REQ" Comment="" dx1="773.3333333333334" dx2="773.3333333333334" dy="0.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="u16ObjId" Destination="Q_BackgroundColour_1.u16ObjId" Comment="" dx1="1460.0"/>
			<Connection Source="u16ObjIdA" Destination="Q_BackgroundColour_2.u16ObjId" Comment="" dx1="160.0"/>
			<Connection Source="u16ObjIdA" Destination="Q_BackgroundColour_3.u16ObjId" Comment="" dx1="133.33333333333334"/>
			<Connection Source="Q_BackgroundColour_3.s16result" Destination="result_3" Comment="" dx1="240.0"/>
			<Connection Source="Q_BackgroundColour_3.u8OldColour" Destination="u8OldColour_3" Comment="" dx1="340.0"/>
			<Connection Source="Q_BackgroundColour_3.STATUS" Destination="STATUS_3" Comment="" dx1="460.0"/>
			<Connection Source="Q_BackgroundColour_2.s16result" Destination="result_2" Comment="" dx1="700.0"/>
			<Connection Source="Q_BackgroundColour_2.u8OldColour" Destination="u8OldColour_2" Comment="" dx1="800.0"/>
			<Connection Source="Q_BackgroundColour_2.STATUS" Destination="STATUS_2" Comment="" dx1="920.0"/>
			<Connection Source="Q_BackgroundColour_1.s16result" Destination="result_1" Comment="" dx1="560.0"/>
			<Connection Source="Q_BackgroundColour_1.u8OldColour" Destination="u8OldColour_1" Comment="" dx1="673.3333333333334"/>
			<Connection Source="Q_BackgroundColour_1.STATUS" Destination="STATUS_1" Comment="" dx1="780.0"/>
			<Connection Source="DI1" Destination="F_SEL_I.G" Comment="" dx1="80.0" dx2="80.0" dy="6.666666666666667"/>
			<Connection Source="F_SEL_I.OUT" Destination="Q_BackgroundColour_1.u8Colour" Comment="" dx1="773.3333333333334" dx2="773.3333333333334" dy="0.0"/>
			<Connection Source="F_SEL_I.OUT" Destination="Q_BackgroundColour_2.u8Colour" Comment="" dx1="773.3333333333334" dx2="773.3333333333334" dy="0.0"/>
			<Connection Source="F_SEL_I.OUT" Destination="Q_BackgroundColour_3.u8Colour" Comment="" dx1="773.3333333333334" dx2="773.3333333333334" dy="0.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
