<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GreenWhiteBackground" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2022-11-10">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="REQ" Type="Event" Comment="Normal Execution Request" >
				<Attribute Name="YPOSITION" Type="INT" Value="175"/>
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF_1" Type="Event" Comment="Execution Confirmation" >
			</SubAppEvent>
			<SubAppEvent Name="CNF_2" Type="Event">
			</SubAppEvent>
			<SubAppEvent Name="CNF_3" Type="Event">
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="DI1" Type="BOOL" Comment="Selector" >
				<Attribute Name="YPOSITION" Type="INT" Value="18"/>
			</VarDeclaration>
			<VarDeclaration Name="u16ObjId" Type="UINT" Comment="Object ID Softkey" >
				<Attribute Name="YPOSITION" Type="INT" Value="45"/>
			</VarDeclaration>
			<VarDeclaration Name="u16ObjIdA" Type="UINT" Comment="Object ID AUX" >
				<Attribute Name="YPOSITION" Type="INT" Value="105"/>
			</VarDeclaration>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="STATUS_1" Type="STRING" Comment="Service Status" />
			<VarDeclaration Name="u8OldColour_1" Type="USINT" Comment="Old value of ID" />
			<VarDeclaration Name="result_1" Type="INT" Comment="retval see description" />
			<VarDeclaration Name="STATUS_2" Type="STRING" Comment="Service Status" >
				<Attribute Name="YPOSITION" Type="INT" Value="33"/>
			</VarDeclaration>
			<VarDeclaration Name="u8OldColour_2" Type="USINT" Comment="Old value of ID" />
			<VarDeclaration Name="result_2" Type="INT" Comment="retval see description" />
			<VarDeclaration Name="STATUS_3" Type="STRING" Comment="Service Status" >
				<Attribute Name="YPOSITION" Type="INT" Value="75"/>
			</VarDeclaration>
			<VarDeclaration Name="u8OldColour_3" Type="USINT" Comment="Old value of ID" />
			<VarDeclaration Name="result_3" Type="INT" Comment="retval see description" />
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Q_BackgroundColour_1" Type="Q_BackgroundColour" x="1600" y="1500">
		</FB>
		<FB Name="Q_BackgroundColour_2" Type="Q_BackgroundColour" x="1600" y="2300">
		</FB>
		<FB Name="Q_BackgroundColour_3" Type="Q_BackgroundColourAux" x="1600" y="3100">
		</FB>
		<FB Name="F_SEL_I" Type="F_SEL" x="-400" y="1400">
			<Parameter Name="IN0" Value="colours::COLOR_WHITE"/>
			<Parameter Name="IN1" Value="colours::COLOR_GREEN"/>
		</FB>
		<EventConnections>
			<Connection Source="Q_BackgroundColour_3.CNF" Destination="CNF_3" dx1="993.33"/>
			<Connection Source="Q_BackgroundColour_2.CNF" Destination="CNF_2" dx1="913.33"/>
			<Connection Source="Q_BackgroundColour_1.CNF" Destination="CNF_1" dx1="380"/>
			<Connection Source="REQ" Destination="F_SEL_I.REQ" dx1="2833.33"/>
			<Connection Source="F_SEL_I.CNF" Destination="Q_BackgroundColour_1.REQ" dx1="773.33"/>
			<Connection Source="F_SEL_I.CNF" Destination="Q_BackgroundColour_2.REQ" dx1="773.33"/>
			<Connection Source="F_SEL_I.CNF" Destination="Q_BackgroundColour_3.REQ" dx1="773.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="u16ObjId" Destination="Q_BackgroundColour_1.u16ObjId" dx1="6400"/>
			<Connection Source="u16ObjIdA" Destination="Q_BackgroundColour_2.u16ObjId" dx1="160"/>
			<Connection Source="u16ObjIdA" Destination="Q_BackgroundColour_3.u16ObjId" dx1="133.33"/>
			<Connection Source="Q_BackgroundColour_3.s16result" Destination="result_3" dx1="240"/>
			<Connection Source="Q_BackgroundColour_3.u8OldColour" Destination="u8OldColour_3" dx1="340"/>
			<Connection Source="Q_BackgroundColour_3.STATUS" Destination="STATUS_3" dx1="460"/>
			<Connection Source="Q_BackgroundColour_2.s16result" Destination="result_2" dx1="700"/>
			<Connection Source="Q_BackgroundColour_2.u8OldColour" Destination="u8OldColour_2" dx1="800"/>
			<Connection Source="Q_BackgroundColour_2.STATUS" Destination="STATUS_2" dx1="920"/>
			<Connection Source="Q_BackgroundColour_1.s16result" Destination="result_1" dx1="560"/>
			<Connection Source="Q_BackgroundColour_1.u8OldColour" Destination="u8OldColour_1" dx1="673.33"/>
			<Connection Source="Q_BackgroundColour_1.STATUS" Destination="STATUS_1" dx1="780"/>
			<Connection Source="DI1" Destination="F_SEL_I.G" dx1="2833.33"/>
			<Connection Source="F_SEL_I.OUT" Destination="Q_BackgroundColour_1.u8Colour" dx1="773.33"/>
			<Connection Source="F_SEL_I.OUT" Destination="Q_BackgroundColour_2.u8Colour" dx1="773.33"/>
			<Connection Source="F_SEL_I.OUT" Destination="Q_BackgroundColour_3.u8Colour" dx1="773.33"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
