<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Ventilsteuerung" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="mapping" Type="mapping" x="-500" y="200">
		</SubApp>
		<SubApp Name="functions" Type="SlurryTanker" x="-500" y="500">
		</SubApp>
		<SubApp Name="PAGES" Type="PAGES" x="-400" y="1000">
		</SubApp>
	</SubAppNetwork>
</SubAppType>
