<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Ventilsteuerung" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-10-23">
	</VersionInfo>
	<CompilerInfo>
	</CompilerInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="mapping" Type="mapping" x="-446.67" y="126.66">
		</SubApp>
		<SubApp Name="functions" Type="SlurryTanker" x="-446.67" y="660">
		</SubApp>
		<SubApp Name="PAGES" Type="PAGES" x="-446.67" y="1193.33">
		</SubApp>
	</SubAppNetwork>
</SubAppType>
