<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Dauerfunktion" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<InputVars>
			<VarDeclaration Name="u16ObjId" Type="UINT"/>
			<VarDeclaration Name="u16ObjIdA" Type="UINT"/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_T_FF" Type="E_T_FF" x="1600" y="100">
		</FB>
		<FB Name="QX" Type="QX" x="4400" y="1000">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<SubApp Name="GreenWhiteBackground_Function" Type="GreenWhiteBackground_Function" x="4400" y="0">
		</SubApp>
		<FB Name="SoftKey" Type="IE" x="-600" y="-400">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="AuxInput" Type="IE" x="-600" y="700">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="E_T_FF.EO" Destination="QX.REQ" dx1="126.67"/>
			<Connection Source="E_T_FF.EO" Destination="GreenWhiteBackground_Function.EO"/>
			<Connection Source="SoftKey.IND" Destination="E_T_FF.CLK" dx1="753.33"/>
			<Connection Source="AuxInput.IND" Destination="E_T_FF.CLK" dx1="753.33"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF.Q" Destination="QX.OUT" dx1="60"/>
			<Connection Source="E_T_FF.Q" Destination="GreenWhiteBackground_Function.Q"/>
			<Connection Source="u16ObjId" Destination="GreenWhiteBackground_Function.u16ObjId" dx1="2866.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="u16ObjIdA" Destination="GreenWhiteBackground_Function.u16ObjIdA" dx1="2866.67">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
