<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Dauerfunktion" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="Service Initialization">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="u16ObjId" Type="UINT" Comment=""/>
			<VarDeclaration Name="u16ObjIdA" Type="UINT" Comment=""/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="E_T_FF" Type="E_T_FF" Comment="" x="1520.0" y="193.33333333333334">
		</FB>
		<FB Name="QX" Type="QX" Comment="" x="2900.0" y="973.3333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
		</FB>
		<SubApp Name="GreenWhiteBackground_Function" Type="GreenWhiteBackground_Function" Comment="" x="4400.0" y="100.0">
		</SubApp>
		<SubApp Name="SoftKey_UP" Type="IE_UP" Comment="" x="-700.0" y="0.0">
		</SubApp>
		<SubApp Name="AuxInput_UP" Type="IN_UP" Comment="" x="-700.0" y="500.0">
		</SubApp>
		<EventConnections>
			<Connection Source="E_T_FF.EO" Destination="QX.REQ" Comment="" dx1="126.66666666666667"/>
			<Connection Source="INIT" Destination="QX.INIT" Comment="" dx1="4113.333333333334">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="GreenWhiteBackground_Function.INIT" Comment="" dx1="5253.333333333334" dx2="5253.333333333334" dy="0.0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="E_T_FF.EO" Destination="GreenWhiteBackground_Function.EO" Comment="" dx1="1160.0" dx2="1160.0" dy="0.0"/>
			<Connection Source="INIT" Destination="SoftKey_UP.INIT" Comment="" dx1="80.0" dx2="80.0" dy="0.0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="SoftKey_UP.IND" Destination="E_T_FF.CLK" Comment="" dx1="786.6666666666667" dx2="786.6666666666667" dy="0.0"/>
			<Connection Source="INIT" Destination="AuxInput_UP.INIT" Comment="" dx1="80.0" dx2="80.0" dy="0.0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="AuxInput_UP.IND" Destination="E_T_FF.CLK" Comment="" dx1="713.3333333333334" dx2="713.3333333333334" dy="0.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="E_T_FF.Q" Destination="QX.OUT" Comment="" dx1="60.0"/>
			<Connection Source="E_T_FF.Q" Destination="GreenWhiteBackground_Function.Q" Comment="" dx1="1160.0" dx2="1160.0" dy="0.0"/>
			<Connection Source="u16ObjId" Destination="GreenWhiteBackground_Function.u16ObjId" Comment="" dx1="2866.666666666667">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
			<Connection Source="u16ObjIdA" Destination="GreenWhiteBackground_Function.u16ObjIdA" Comment="" dx1="2866.666666666667">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
