<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Knickdeichsel_Sitzventile" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-11">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INITO" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="CNF_Knickdeichsel_heben" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="CNF_Knickdeichsel_senken" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="IN_Knickdeichsel_heben" Type="BOOL" Comment=""/>
			<VarDeclaration Name="IN_Knickdeichsel_senken" Type="BOOL" Comment=""/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="OR_2" Type="OR_2" Comment="" x="673.3333333333334" y="566.6666666666667">
			<Attribute Name="PinComment" Type="STRING" Value="IN1:Knickdeichsel_heben"/>
			<Attribute Name="PinComment" Type="STRING" Value="IN2:Knickdeichsel_senken"/>
		</FB>
		<FB Name="Knickdeichsel_5B" Type="QX" Comment="" x="2006.6666666666667" y="173.33333333333334">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Knickdeichsel_5A" Type="QX" Comment="" x="2006.6666666666667" y="1240.0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="OR_2.CNF" Destination="Knickdeichsel_5B.REQ" Comment="" dx1="333.33333333333337"/>
			<Connection Source="OR_2.CNF" Destination="Knickdeichsel_5A.REQ" Comment="" dx1="300.0"/>
			<Connection Source="CNF_Knickdeichsel_heben" Destination="OR_2.REQ" Comment="" dx1="1066.6666666666667"/>
			<Connection Source="CNF_Knickdeichsel_senken" Destination="OR_2.REQ" Comment="" dx1="960.0"/>
			<Connection Source="INITO" Destination="Knickdeichsel_5B.INIT" Comment="" dx1="3366.666666666667"/>
			<Connection Source="INITO" Destination="Knickdeichsel_5A.INIT" Comment="" dx1="3366.666666666667"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="OR_2.OUT" Destination="Knickdeichsel_5B.OUT" Comment="" dx1="406.6666666666667"/>
			<Connection Source="OR_2.OUT" Destination="Knickdeichsel_5A.OUT" Comment="" dx1="193.33333333333334"/>
			<Connection Source="IN_Knickdeichsel_heben" Destination="OR_2.IN1" Comment="" dx1="853.3333333333334"/>
			<Connection Source="IN_Knickdeichsel_senken" Destination="OR_2.IN2" Comment="" dx1="746.6666666666667"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
