<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Knickdeichsel" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="IND_2b" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="IND_2a" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventOutputs>
		<OutputVars>
			<VarDeclaration Name="OUT_2b" Type="BOOL" Comment=""/>
			<VarDeclaration Name="OUT_2a" Type="BOOL" Comment=""/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="SoftKey_Knickdeichsel_heben" Type="IX" Comment="" x="353.33333333333337" y="253.33333333333334">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="SoftKey_Knickdeichsel_senken" Type="IX" Comment="" x="353.33333333333337" y="1453.3333333333335">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<SubApp Name="GreenWhiteBackground_Knickdeichsel_heben" Comment="" x="3466.666666666667" y="533.3333333333334">
			<SubAppInterfaceList>
				<SubAppEventInputs>
					<SubAppEvent Name="INIT" Type="Event" Comment="">
					</SubAppEvent>
					<SubAppEvent Name="IND" Type="Event" Comment="">
					</SubAppEvent>
				</SubAppEventInputs>
				<InputVars>
					<VarDeclaration Name="IN" Type="BOOL" Comment=""/>
				</InputVars>
			</SubAppInterfaceList>
			<SubAppNetwork>
				<FB Name="GreenWhiteBackground_Knickdeichsel_heben" Type="GreenWhiteBackground" Comment="" x="0.0" y="0.0">
					<Parameter Name="u16ObjId" Value="5011"/>
				</FB>
				<EventConnections>
					<Connection Source="INIT" Destination="GreenWhiteBackground_Knickdeichsel_heben.INIT" Comment="" dx1="80.0" dx2="80.0" dy="-13.333333333333334"/>
					<Connection Source="IND" Destination="GreenWhiteBackground_Knickdeichsel_heben.REQ" Comment="" dx1="80.0" dx2="80.0" dy="-13.333333333333334"/>
				</EventConnections>
				<DataConnections>
					<Connection Source="IN" Destination="GreenWhiteBackground_Knickdeichsel_heben.DI1" Comment="" dx1="80.0" dx2="80.0" dy="93.33333333333334"/>
				</DataConnections>
			</SubAppNetwork>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="GreenWhiteBackground_Knickdeichsel_senken" Comment="" x="3466.666666666667" y="1466.6666666666667">
			<SubAppInterfaceList>
				<SubAppEventInputs>
					<SubAppEvent Name="INIT" Type="Event" Comment="">
					</SubAppEvent>
					<SubAppEvent Name="IND" Type="Event" Comment="">
					</SubAppEvent>
				</SubAppEventInputs>
				<InputVars>
					<VarDeclaration Name="IN" Type="BOOL" Comment=""/>
				</InputVars>
			</SubAppInterfaceList>
			<SubAppNetwork>
				<FB Name="GreenWhiteBackground_Knickdeichsel_senken" Type="GreenWhiteBackground" Comment="" x="0.0" y="0.0">
					<Parameter Name="u16ObjId" Value="5005"/>
				</FB>
				<EventConnections>
					<Connection Source="INIT" Destination="GreenWhiteBackground_Knickdeichsel_senken.INIT" Comment=""/>
					<Connection Source="IND" Destination="GreenWhiteBackground_Knickdeichsel_senken.REQ" Comment=""/>
				</EventConnections>
				<DataConnections>
					<Connection Source="IN" Destination="GreenWhiteBackground_Knickdeichsel_senken.DI1" Comment=""/>
				</DataConnections>
			</SubAppNetwork>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="Knickdeichsel_Sitzventile" Type="Knickdeichsel_Sitzventile" Comment="" x="5146.666666666667" y="2120.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<EventConnections>
			<Connection Source="INIT" Destination="SoftKey_Knickdeichsel_heben.INIT" Comment="" dx1="866.6666666666667"/>
			<Connection Source="SoftKey_Knickdeichsel_heben.IND" Destination="IND_2b" Comment="" dx1="1153.3333333333335"/>
			<Connection Source="INIT" Destination="SoftKey_Knickdeichsel_senken.INIT" Comment="" dx1="760.0"/>
			<Connection Source="SoftKey_Knickdeichsel_senken.IND" Destination="IND_2a" Comment="" dx1="1213.3333333333335"/>
			<Connection Source="INIT" Destination="GreenWhiteBackground_Knickdeichsel_heben.INIT" Comment="" dx1="5133.333333333334"/>
			<Connection Source="SoftKey_Knickdeichsel_heben.IND" Destination="GreenWhiteBackground_Knickdeichsel_heben.IND" Comment="" dx1="1106.6666666666667"/>
			<Connection Source="INIT" Destination="GreenWhiteBackground_Knickdeichsel_senken.INIT" Comment="" dx1="5133.333333333334"/>
			<Connection Source="SoftKey_Knickdeichsel_senken.IND" Destination="GreenWhiteBackground_Knickdeichsel_senken.IND" Comment="" dx1="1093.3333333333335"/>
			<Connection Source="INIT" Destination="Knickdeichsel_Sitzventile.INIT" Comment="" dx1="6393.333333333334" dx2="6393.333333333334" dy="0.0"/>
			<Connection Source="SoftKey_Knickdeichsel_senken.IND" Destination="Knickdeichsel_Sitzventile.IND_Knickdeichsel_senken" Comment="" dx1="573.3333333333334" dx2="573.3333333333334" dy="0.0"/>
			<Connection Source="SoftKey_Knickdeichsel_heben.IND" Destination="Knickdeichsel_Sitzventile.IND_Knickdeichsel_heben" Comment="" dx1="513.3333333333334" dx2="513.3333333333334" dy="0.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="SoftKey_Knickdeichsel_heben.IN" Destination="OUT_2b" Comment="" dx1="1366.6666666666667"/>
			<Connection Source="SoftKey_Knickdeichsel_senken.IN" Destination="OUT_2a" Comment="" dx1="1426.6666666666667"/>
			<Connection Source="SoftKey_Knickdeichsel_heben.IN" Destination="GreenWhiteBackground_Knickdeichsel_heben.IN" Comment="" dx1="1106.6666666666667"/>
			<Connection Source="SoftKey_Knickdeichsel_senken.IN" Destination="GreenWhiteBackground_Knickdeichsel_senken.IN" Comment="" dx1="1093.3333333333335"/>
			<Connection Source="SoftKey_Knickdeichsel_heben.IN" Destination="Knickdeichsel_Sitzventile.IN_Knickdeichsel_heben" Comment="" dx1="406.6666666666667" dx2="406.6666666666667" dy="0.0"/>
			<Connection Source="SoftKey_Knickdeichsel_senken.IN" Destination="Knickdeichsel_Sitzventile.IN_Knickdeichsel_senken" Comment="" dx1="253.33333333333334" dx2="253.33333333333334" dy="0.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
