<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Knickdeichsel_Sitzventile" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-11">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="IND_Knickdeichsel_senken" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="IND_Knickdeichsel_heben" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="IN_Knickdeichsel_heben" Type="BOOL" Comment=""/>
			<VarDeclaration Name="IN_Knickdeichsel_senken" Type="BOOL" Comment=""/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="OR_5A_5B" Type="OR_2" Comment="" x="493.33333333333337" y="333.33333333333337">
			<Attribute Name="PinComment" Type="STRING" Value="IN1:Knickdeichsel_heben"/>
			<Attribute Name="PinComment" Type="STRING" Value="IN2:Knickdeichsel_senken"/>
		</FB>
		<FB Name="Knickdeichsel_5B" Type="QX" Comment="" x="1553.3333333333335" y="66.66666666666667">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<FB Name="Knickdeichsel_5A" Type="QX" Comment="" x="1553.3333333333335" y="1133.3333333333335">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="OR_5A_5B.CNF" Destination="Knickdeichsel_5B.REQ" Comment="" dx1="293.33333333333337"/>
			<Connection Source="OR_5A_5B.CNF" Destination="Knickdeichsel_5A.REQ" Comment="" dx1="206.66666666666669"/>
			<Connection Source="IND_Knickdeichsel_senken" Destination="OR_5A_5B.REQ" Comment="" dx1="2500.0" dx2="160.0" dy="-86.66666666666667"/>
			<Connection Source="IND_Knickdeichsel_heben" Destination="OR_5A_5B.REQ" Comment="" dx1="2393.3333333333335" dx2="53.333333333333336" dy="-186.66666666666669"/>
			<Connection Source="INIT" Destination="Knickdeichsel_5B.INIT" Comment="" dx1="1500.0"/>
			<Connection Source="INIT" Destination="Knickdeichsel_5A.INIT" Comment="" dx1="2713.3333333333335" dx2="53.333333333333336" dy="873.3333333333334"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="OR_5A_5B.OUT" Destination="Knickdeichsel_5B.OUT" Comment="" dx1="313.33333333333337"/>
			<Connection Source="OR_5A_5B.OUT" Destination="Knickdeichsel_5A.OUT" Comment="" dx1="100.0"/>
			<Connection Source="IN_Knickdeichsel_heben" Destination="OR_5A_5B.IN1" Comment="" dx1="2606.666666666667" dx2="333.33333333333337" dy="-286.6666666666667"/>
			<Connection Source="IN_Knickdeichsel_senken" Destination="OR_5A_5B.IN2" Comment="" dx1="2820.0" dx2="333.33333333333337" dy="580.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
