<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="GreenWhiteBackground_Function" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-06">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="20"/>
			</SubAppEvent>
			<SubAppEvent Name="EO" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="272"/>
			</SubAppEvent>
		</SubAppEventInputs>
		<InputVars>
			<VarDeclaration Name="Q" Type="BOOL" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="139"/>
			</VarDeclaration>
			<VarDeclaration Name="u16ObjId" Type="UINT" Comment=""/>
			<VarDeclaration Name="u16ObjIdA" Type="UINT" Comment=""/>
		</InputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="GreenWhiteBackground_Dom" Type="GreenWhiteBackground" Comment="" x="-2533.3333333333335" y="-3466.666666666667">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<EventConnections>
			<Connection Source="EO" Destination="GreenWhiteBackground_Dom.REQ" Comment="" dx1="573.3333333333334" dx2="573.3333333333334" dy="0.0"/>
			<Connection Source="INIT" Destination="GreenWhiteBackground_Dom.INIT" Comment="" dx1="766.6666666666667" dx2="766.6666666666667" dy="0.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="Q" Destination="GreenWhiteBackground_Dom.DI1" Comment="" dx1="680.0" dx2="680.0" dy="0.0"/>
			<Connection Source="u16ObjId" Destination="GreenWhiteBackground_Dom.u16ObjId" Comment="" dx1="733.3333333333334"/>
			<Connection Source="u16ObjIdA" Destination="GreenWhiteBackground_Dom.u16ObjIdA" Comment="" dx1="833.3333333333334"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
