<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="AuxInput_Verteiler_senken" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-11">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="IND" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventOutputs>
		<OutputVars>
			<VarDeclaration Name="IN" Type="BOOL" Comment=""/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="AuxInput_Verteiler_senken" Type="IX" Comment="" x="0.0" y="0.0">
			<Parameter Name="QI" Value="TRUE"/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="AuxInput_Verteiler_senken.INIT" Comment="" dx1="80.0" dx2="80.0" dy="33.333333333333336"/>
			<Connection Source="AuxInput_Verteiler_senken.IND" Destination="IND" Comment="" dx1="2913.3333333333335"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="AuxInput_Verteiler_senken.IN" Destination="IN" Comment="" dx1="2913.3333333333335"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
