<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="Verteiler" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="EI_Verteiler_heben" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="EI_Verteiler_senken" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
		<SubAppEventOutputs>
			<SubAppEvent Name="CNF_2b" Type="Event" Comment="">
			</SubAppEvent>
			<SubAppEvent Name="CNF_2a" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventOutputs>
		<InputVars>
			<VarDeclaration Name="IN_Verteiler_heben" Type="BOOL" Comment=""/>
			<VarDeclaration Name="IN_Verteiler_senken" Type="BOOL" Comment=""/>
		</InputVars>
		<OutputVars>
			<VarDeclaration Name="OUT_2b" Type="BOOL" Comment=""/>
			<VarDeclaration Name="OUT_2a" Type="BOOL" Comment=""/>
		</OutputVars>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="GreenWhiteBackground_Verteiler_heben" Type="GreenWhiteBackground_Verteiler_heben" Comment="" x="3800.0" y="3300.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="GreenWhiteBackground_Verteiler_senken" Type="GreenWhiteBackground_Verteiler_senken" Comment="" x="3800.0" y="4000.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="Verteiler_Sitzventile" Type="Verteiler_Sitzventile" Comment="" x="5926.666666666667" y="2520.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<FB Name="OR_2_Verteiler_heben" Type="OR_3" Comment="" x="2300.0" y="700.0">
		</FB>
		<FB Name="OR_2_Verteiler_senken" Type="OR_3" Comment="" x="2200.0" y="2100.0">
		</FB>
		<SubApp Name="SoftKey_Verteiler_heben" Type="SoftKey_Verteiler_heben" Comment="" x="-200.0" y="500.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="SoftKey_Verteiler_senken" Type="SoftKey_Verteiler_senken" Comment="" x="-200.0" y="1500.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="AuxInput_Verteiler_heben" Type="SoftKey_Verteiler_heben" Comment="" x="-200.0" y="1000.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="AuxInput_Verteiler_senken" Type="AuxInput_Verteiler_senken" Comment="" x="-200.0" y="2000.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<EventConnections>
			<Connection Source="INIT" Destination="GreenWhiteBackground_Verteiler_heben.INIT" Comment="" dx1="5046.666666666667"/>
			<Connection Source="INIT" Destination="GreenWhiteBackground_Verteiler_senken.INIT" Comment="" dx1="5046.666666666667"/>
			<Connection Source="INIT" Destination="Verteiler_Sitzventile.INITO" Comment="" dx1="6906.666666666667" dx2="5886.666666666667" dy="0.0"/>
			<Connection Source="EI_Verteiler_heben" Destination="OR_2_Verteiler_heben.REQ" Comment="" dx1="3566.666666666667"/>
			<Connection Source="OR_2_Verteiler_heben.CNF" Destination="CNF_2a" Comment="" dx1="5586.666666666667"/>
			<Connection Source="OR_2_Verteiler_heben.CNF" Destination="GreenWhiteBackground_Verteiler_heben.CNF" Comment="" dx1="606.6666666666667"/>
			<Connection Source="OR_2_Verteiler_heben.CNF" Destination="Verteiler_Sitzventile.CNF_Verteiler_heben" Comment="" dx1="2506.666666666667"/>
			<Connection Source="EI_Verteiler_senken" Destination="OR_2_Verteiler_senken.REQ" Comment="" dx1="3406.666666666667"/>
			<Connection Source="OR_2_Verteiler_senken.CNF" Destination="CNF_2b" Comment="" dx1="5333.333333333334"/>
			<Connection Source="OR_2_Verteiler_senken.CNF" Destination="GreenWhiteBackground_Verteiler_senken.CNF" Comment="" dx1="453.33333333333337"/>
			<Connection Source="OR_2_Verteiler_senken.CNF" Destination="Verteiler_Sitzventile.CNF_Verteiler_senken" Comment="" dx1="1880.0"/>
			<Connection Source="INIT" Destination="SoftKey_Verteiler_heben.INIT" Comment="" dx1="713.3333333333334"/>
			<Connection Source="SoftKey_Verteiler_heben.IND" Destination="OR_2_Verteiler_heben.REQ" Comment="" dx1="413.33333333333337"/>
			<Connection Source="INIT" Destination="SoftKey_Verteiler_senken.INIT" Comment="" dx1="713.3333333333334"/>
			<Connection Source="SoftKey_Verteiler_senken.IND" Destination="OR_2_Verteiler_senken.REQ" Comment="" dx1="760.0"/>
			<Connection Source="INIT" Destination="AuxInput_Verteiler_heben.INIT" Comment="" dx1="713.3333333333334"/>
			<Connection Source="AuxInput_Verteiler_heben.IND" Destination="OR_2_Verteiler_heben.REQ" Comment="" dx1="413.33333333333337"/>
			<Connection Source="INIT" Destination="AuxInput_Verteiler_senken.INIT" Comment="" dx1="713.3333333333334" dx2="713.3333333333334" dy="0.0"/>
			<Connection Source="AuxInput_Verteiler_senken.IND" Destination="OR_2_Verteiler_senken.REQ" Comment="" dx1="600.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="IN_Verteiler_heben" Destination="OR_2_Verteiler_heben.IN2" Comment="" dx1="3246.666666666667"/>
			<Connection Source="OR_2_Verteiler_heben.OUT" Destination="OUT_2a" Comment="" dx1="6093.333333333334"/>
			<Connection Source="OR_2_Verteiler_heben.OUT" Destination="GreenWhiteBackground_Verteiler_heben.OUT" Comment="" dx1="493.33333333333337"/>
			<Connection Source="OR_2_Verteiler_heben.OUT" Destination="Verteiler_Sitzventile.IN_Verteiler_heben" Comment="" dx1="1620.0"/>
			<Connection Source="IN_Verteiler_senken" Destination="OR_2_Verteiler_senken.IN2" Comment="" dx1="173.33333333333334"/>
			<Connection Source="OR_2_Verteiler_senken.OUT" Destination="OUT_2b" Comment="" dx1="5893.333333333334"/>
			<Connection Source="OR_2_Verteiler_senken.OUT" Destination="GreenWhiteBackground_Verteiler_senken.OUT" Comment="" dx1="360.0"/>
			<Connection Source="OR_2_Verteiler_senken.OUT" Destination="Verteiler_Sitzventile.IN_Verteiler_senken" Comment="" dx1="1500.0"/>
			<Connection Source="SoftKey_Verteiler_heben.IN" Destination="OR_2_Verteiler_heben.IN1" Comment="" dx1="213.33333333333334"/>
			<Connection Source="SoftKey_Verteiler_senken.IN" Destination="OR_2_Verteiler_senken.IN1" Comment="" dx1="426.6666666666667"/>
			<Connection Source="AuxInput_Verteiler_heben.IN" Destination="OR_2_Verteiler_heben.IN3" Comment="" dx1="566.6666666666667"/>
			<Connection Source="AuxInput_Verteiler_senken.IN" Destination="OR_2_Verteiler_senken.IN3" Comment="" dx1="246.66666666666669"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
