<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="PAGES" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="franz" Date="2023-02-06">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
				<Attribute Name="YPOSITION" Type="STRING" Value="100"/>
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<SubApp Name="PAGE_1" Type="PAGE_1" Comment="" x="0.0" y="0.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="PAGE_2" Type="PAGE_2" Comment="" x="0.0" y="533.3333333333334">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<FB Name="Q_SoftKeyMask" Type="Q_SoftKeyMask" Comment="" x="4933.333333333334" y="-1066.6666666666667">
			<Parameter Name="u8MaskType" Value="1"/>
			<Parameter Name="u16DataMaskId" Value="DataMask_1000"/>
		</FB>
		<SubApp Name="VT_active" Type="VT_active" Comment="" x="-800.0" y="-1100.0">
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<FB Name="F_SEL_I" Type="F_SEL_E_2" Comment="" x="3100.0" y="-1100.0">
			<Parameter Name="IN0" Value="SoftKeyMask_PAGE_1"/>
			<Parameter Name="IN1" Value="SoftKeyMask_PAGE_2"/>
		</FB>
		<FB Name="E_SR_PAGE_1" Type="E_SR" Comment="" x="3600.0" y="700.0">
		</FB>
		<FB Name="E_SR_PAGE_2" Type="E_SR" Comment="" x="3500.0" y="2700.0">
		</FB>
		<SubApp Name="GreenWhiteBackground_PAGE_2" Type="GreenWhiteBackground" Comment="" x="5066.666666666667" y="2533.3333333333335">
			<Parameter Name="u16ObjId" Value="PAGE_2_BTN"/>
			<Parameter Name="u16ObjIdA" Value="PAGE_2_AUX"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<SubApp Name="GreenWhiteBackground_PAGE_1" Type="GreenWhiteBackground" Comment="" x="5066.666666666667" y="533.3333333333334">
			<Parameter Name="u16ObjId" Value="PAGE_1_BTN"/>
			<Parameter Name="u16ObjIdA" Value="PAGE_1_AUX"/>
			<Attribute Name="width" Type="LREAL" Value="1333.3333333333335"/>
			<Attribute Name="height" Type="LREAL" Value="666.6666666666667"/>
		</SubApp>
		<EventConnections>
			<Connection Source="INIT" Destination="PAGE_1.INIT" Comment="" dx1="400.0" dx2="400.0" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="PAGE_2.INIT" Comment="" dx1="666.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="F_SEL_I.CNF" Destination="Q_SoftKeyMask.REQ" Comment="" dx1="446.6666666666667"/>
			<Connection Source="VT_active.EO" Destination="F_SEL_I.REQ0" Comment=""/>
			<Connection Source="PAGE_1.IND" Destination="F_SEL_I.REQ0" Comment="" dx1="1033.3333333333335"/>
			<Connection Source="PAGE_2.IND" Destination="F_SEL_I.REQ1" Comment="" dx1="1326.6666666666667"/>
			<Connection Source="VT_active.EO" Destination="E_SR_PAGE_1.S" Comment="" dx1="1860.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="PAGE_1.IND" Destination="E_SR_PAGE_1.S" Comment="" dx1="1526.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="PAGE_2.IND" Destination="E_SR_PAGE_2.S" Comment="" dx1="1480.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="PAGE_1.IND" Destination="E_SR_PAGE_2.R" Comment="" dx1="1480.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="VT_active.EO" Destination="E_SR_PAGE_2.R" Comment="" dx1="1806.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="PAGE_2.IND" Destination="E_SR_PAGE_1.R" Comment="" dx1="1526.6666666666667">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="INIT" Destination="GreenWhiteBackground_PAGE_2.INIT" Comment="" dx1="3213.3333333333335" dx2="3213.3333333333335" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="E_SR_PAGE_2.EO" Destination="GreenWhiteBackground_PAGE_2.REQ" Comment="" dx1="546.6666666666667" dx2="546.6666666666667" dy="0.0"/>
			<Connection Source="INIT" Destination="GreenWhiteBackground_PAGE_1.INIT" Comment="" dx1="3000.0" dx2="3000.0" dy="0.0">
				<Attribute Name="Visible" Type="STRING" Value="false"/>
			</Connection>
			<Connection Source="E_SR_PAGE_1.EO" Destination="GreenWhiteBackground_PAGE_1.REQ" Comment="" dx1="500.0" dx2="500.0" dy="0.0"/>
		</EventConnections>
		<DataConnections>
			<Connection Source="F_SEL_I.OUT" Destination="Q_SoftKeyMask.u16SoftKeyMaskId" Comment="" dx1="180.0"/>
			<Connection Source="E_SR_PAGE_2.Q" Destination="GreenWhiteBackground_PAGE_2.DI1" Comment="" dx1="546.6666666666667" dx2="546.6666666666667" dy="0.0"/>
			<Connection Source="E_SR_PAGE_1.Q" Destination="GreenWhiteBackground_PAGE_1.DI1" Comment="" dx1="500.0" dx2="500.0" dy="0.0"/>
		</DataConnections>
	</SubAppNetwork>
</SubAppType>
